db/migrate/20160911143333_add_volume_issue_to_papers.rb
db/schema.rb
lib/tasks/bib_export.rake
lib/tasks/xml_import.rake

Fixes issue #18   
Here is a patch to add volume and issue numbers to the
database and to the generated bibtex.  It will accept
<volume> and <issue> tags in the ingested xml files,
but it also figures out the volume and issue numbers
from the current xml files.

add issue and volume numbers for journal articles

---

lib/tasks/bib_export.rake

commit [3f13e3ba39ff210a3b20d025c4c6c80ec29e116f] updated the
bibutils source files, but it appears that the production server
is still running the old executable for xml2bib.
this commit hardcodes the location of the bibutils executables,
so that being able to find them does not depend on the user's PATH.
this commit also compiles bibutils automatically if the executables
are not found.
please check that this fixes the problem that the bibtex files on the production
server say "Smith, A. Noah" instead of "Smith, Noah A.".

hardcode bibutils path

---

lib/tasks/bib_export.rake

Fixes #46
"workshop publication" does not seem to be a recognized mods genre:
http://www.loc.gov/standards/valuelist/marcgt.html
and results in bibutils making a @Misc entry
instead of an @InProceedings entry.

use "conference publication" as mods xml genre for workshops

---

import/H86.xml
import/W08.xml

Fixing mis-parsed entries, on the assumption that this XML data is the master source for everything and therefore the right place to fix it.

fixed mis-parsed author and title info

---

import/escapeXML.pl

Follow-up to #53. 
* This adds several escapes (HTML entity replacements) to the `escapeXML.pl` script from that PR
Separated out for a subsequent PR:
* (Re-)Running the improved `escapeXML.pl` (which processes all `.xml` files in the `import` folder)
* Such that `xmllint --noout import/*.xml` returns successfully (reports no errors)

Add several replacements to escapeXML.pl script

---

import/schema.rnc
import/schema.rng

This PR provides a schema to check the integrity of the data in `import/*.xml`.
It will benefit from further changes, e.g., to reflect structural changes in #75, but the basic advantage is that it picks up on obviously unintended artifacts, as well as your run-of-the-mill XML syntax violations (e.g., the entity issues fixed by `escapeXML.pl` and #61).
_Most_ of the `import/*.xml` files validate just fine. Supposing #61 gets merged and re-run, the remaining errors picked out by this schema should be trivial to fix manually. These can be listed by running this command from the `import/` directory:
```shell
xmllint --relaxng schema.rng --noout *.xml
```
What follows are some snippets resulting from running that command:
```console
C02.xml validates
C04.xml:263: element paper: Relax-NG …
```

Add RELAX NG schema

---

import/C04.xml
import/E06.xml
import/H93.xml
import/J02.xml
import/J16.xml
import/J17.xml
import/Q15.xml
import/W98.xml

These changes bring all the data in `import/*.xml` into compliance with `schema.rng` from #76.

Remove text appearing outside expected elements

---

import/D18.xml
import/J92.xml
import/K18.xml
import/W17.xml
import/W18.xml
import/W19.xml
import/Y03.xml
import/Y04.xml
import/Y96.xml
import/schema.rnc
import/schema.rng

This PR improves the authoritative XML in the following ways:
1. Fix errors described in #127 
2. Run the `bin/parsenames.pl` script on some XML files that were missing `<first></first><last></last>` elements. This is already causing issues on the live website; for example, [Martin van Schijndel](https://aclanthology.info/people/marten-van-schijndel-303a8589-195c-418f-9bf5-701221d96858) who published in W19 is not considered to be the same person as [Martin van Schijndel](https://aclanthology.info/people/marten-van-schijndel-bcdb2fd2-ba5a-4fa6-b91b-c9f246068d52).
3. Tighten up the RelaxNG schema. This involves:
a) Enforcing that all person names must have `<first></first><last></last>` (and optionally `<jr></jr>`) annotations.
b) Removing the deprecated `<von>` element.
c) Making explicit …

Improvements to the authoritative XML

---

import/D18.xml

The abstracts are exactly as they appeared on the conference website; no attempt was made to process TeX control sequences or special characters (\%, ``, '', etc.).
A few titles were also fixed:
- "Percent" changed to "%" to match the title in the PDF
- A curly apostrophe changed to a straight one
- Removed a trailing period

Added abstracts to EMNLP 2018 (D18). Also fixed a few titles.

---

bin/anthology.py
bin/requirements.txt
bin/xml_to_yaml.py

This PR adds a script that converts the authoritative XML to YAML format, in preparation for using these files as a data source in the static rewrite of the site.
+ `anthology.py` contains classes that read in the XML and represent it as simple Python objects. They might potentially be useful for further checks or conversions as well.
+ `xml_to_yaml.py` outputs one YAML file per XML file with the paper infos, and additionally compiles an author index in a separate YAML file. This is done to facilitate the generation of the static pages, and might be extended with other auxiliary files in the future. Conflation of name variants could, in principle, also be done at this point, depending on how exactly we decide to handle them ( #86 ).
I will continue to add to and/or modify these scripts …

Scripts for XML -> Python object -> YAML conversion (re #129)

---

import/siglex.yaml

These events were, until now, only listed under SIGSEM. However, they are co-organized by SIGLEX. (See e-mail disscussion.)

Added missing SemEval, *SEM entries for 2016, 2018

---

bin/anthology/data.py
bin/anthology/utils.py
hugo/static/.htaccess

Creates a canonical path for attachments. Also adjusts the canonical URL to be HTTPS instead of HTTP.
Related to #216.

canonical path for attachments

---

hugo/static/.htaccess

We weren't properly redirecting the following to the new file location under `/anthology-files/pdf`
- volumes
- pdf extensions on the canonical URL
- revisions
- the old canonical path (e.g., https://www.aclweb.org/anthology/E/E14/E14-1049.pdf)

added missing redirects, added formatting (#215)

---

bin/auto_first_names.py
data/xml/H01.xml
data/xml/L06.xml
data/xml/schema.rnc
data/xml/schema.rng

For the most part, the first names were scraped from the PDF files, and then manually checked. The scraper is bin/auto_first_names.py.
A few other corrections were made as well.
Closes #224, although there are a few much smaller conferences that have the same problem.

Add first names to L06.xml

---

data/xml/C02.xml
data/xml/C88.xml
data/xml/C90.xml
data/xml/C94.xml
data/xml/I08.xml
data/xml/L00.xml
data/xml/L02.xml
data/xml/L04.xml
data/xml/L10.xml
data/xml/W15.xml
data/xml/W97.xml
data/yaml/name_variants.yaml

- Corrections from LREC organizers (no full first names yet)
- A couple of further corrections for the Della Pietras (2de24587ea9ed6e6868d3c6224767c286fc9d001), and updated name_variants.yaml
- Updated name_variants.yaml for Di Eugenio (b29ce76b828e7dc81927b4a4a08d0a195359c912)

Corrections to author names and name variants

---

bin/repair_url.py
data/xml/L10.xml
data/xml/L12.xml
data/xml/L14.xml
data/xml/L18.xml

For L18, the `<url>` elements were rewritten to the correct URLs.
For L10, L12, L14, the `<url>` elements were removed.
The added script actually checks whether the URLs are dead or not, but I didn't use this in the end; the reason is that some papers on the LREC website are 404 (not sure why) and that didn't seem like a good reason to remove the link.

Repair URLs in LREC

---

bin/check_name_variants.py
data/xml/L00.xml
data/xml/L02.xml
data/xml/L04.xml
data/xml/L06.xml
data/xml/L08.xml
data/xml/L12.xml
data/xml/W11.xml
data/xml/schema.rnc
data/xml/schema.rng
data/yaml/name_variants.yaml

Here's what the full first names look like using the `complete` attribute. The `name_variants.yaml` has been updated to include both the abbreviated and complete names, but in my opinion it should eventually include only the complete names.
Currently the `complete` attribute doesn't show up anywhere; the easiest way to enable it would be to modify `anthology.people.PersonName.from_element()` to substitute in the value of the `complete` attribute if it exists, but I'll defer to @mbollmann for the right way to do it.
Also (of course) there are a handful of other corrections to the XML.
Closes #245

Full first names for some LREC conferences; new `complete` attribute

---

data/xml/W13.xml

See issue #236 
The page numbers for the papers are as they appear in the files, which is not the same as the PDF page numbers due to roman numerals in the front matter (off by 3).

add iwpt 2013 proceedings

---

bin/requirements.txt

New 0.2.0 release of TeXSoup breaks the build.

Hotfix requirements.txt

---

data/xml/H90.xml
data/xml/H92.xml
data/xml/H94.xml
data/xml/P93.xml
data/xml/W13.xml
data/xml/W14.xml
data/yaml/name_variants.yaml

The first commit here eliminates the square brackets in one author's name that I thought was too collision prone (discussed at https://github.com/acl-org/acl-anthology/pull/217#issuecomment-479718771).
The second commit uses the `complete` attribute to resolve the ambiguous author name "Robert Mercer" (discussed at #208). My thought is that in this type of situation, the `complete` attribute is sufficient for disambiguation, and this is the right way to do it. I'm trying out this one case so you can see how it looks. If it looks good, there's at least one other I'm aware of, but probably more.

Filling in a few first names

---

bin/build_hugo
bin/xml2end_wrapper
hugo/layouts/papers/single.html
hugo/layouts/volumes/single.html

This is a pull request to add EndNote citation support to the site. This is in response to Issue #235.
The code ...
1. creates a new wrapper, `xml2end_wrapper`, that follows the format of the wrapper used for Bib2XML. 
2. adds a step in `bin/build_hugo` to generate all .endf files
3. updates the templates in `papers/single.html` and `volumes/single-html` to add a new citation export button
An important detail about this Pull Request: my computer is not powerful enough to run Hugo to the end, and therefore I cannot fully verify that the HTML files are built properly. I have checked that the generated files look fine, and I have also checked that the HTML files that manage to get generated look as one would expect. But I can't run the process all the way to the end.

Adds support for the EndNote citation format

---

bin/build_hugo

As a result of PR #270 incorporating the EndNote citation format, we should now ensure that `xml2end` exists in the system. This PR adds that one check, as suggested in the PR discussion.

Added a missing check to ensure that the executable for xml2end exists

---

data/xml/W01.xml
data/yaml/sigs/sigparse.yaml

I prepared IWPT2001 for ingestion. An archive with the pdfs is at
http://blog.gebhardt.xyz/assets/IWPT2001-anthology.zip
`W01-1800.pdf` currently only contains the front matter. The indiviual papers do not have an imprint. 
If someone gives me a pointer where this functionality is hidden in aclpub I may compile a single pdf (including the author index) and pdfs with imprint as well.

W01-18XX: ingestion of IWPT 2001 (see #286)

---

bin/anthology/index.py
bin/create_hugo_yaml.py
data/xml/L02.xml
data/xml/P05.xml
data/yaml/name_variants.yaml
hugo/layouts/people/single.html

The typical form of the comment is semicolon separated values, all optional:
- Name in another script (so far only Chinese)
- Affiliations, separated by commas
- `d. 1973` (for `anthology/people/j/jaime-r-carbonell/`, to make it really clear that it's not CMU Jaime, because they were both at BBN at one point).
For an author name which is known to be ambiguous (e.g., `anthology/people/y/yang-liu`), the comment is "May refer to several people". Changes in wording welcome.

Display author comments and similar names

---

data/xml/W13.xml
data/yaml/name_variants.yaml

In fact, the only occurrence of "Jim Rogers" in the anthology (`W13-3007`) is only in the BibTex (the paper says James). However, he published as "Jim Rogers" elsewhere, e.g.: https://link.springer.com/article/10.1007/s10849-011-9134-0

name variant {James,Jim} Rogers

---

hugo/layouts/_default/baseof.html

The yellow warning banner is always too close to the page. This will add a little space. This time, it uses bootstrap utilities without adding new classes.

Add spacing to warning banner.

---

data/yaml/sigs/sigfsm.yaml

added missing link to FSMNLP 2017 on the page of SIGFSM

SIGFSM: link to FSMNLP 2017

---

bin/requirements.txt

This fixes an error when installing the dependencies
using pip3 install -r requirements.txt and not having
wheels installed system-wide.
Noticed it because the stop words package threw an error
not finding bdist_wheel.

Make sure that wheels are installed

---

.gitignore
.travis.yml
Makefile
README.md
README_detailed.md
bin/bib2xml_wrapper
bin/create_bibtex.py
bin/create_hugo_pages.py
bin/create_hugo_yaml.py
hugo/config.toml
hugo/index.html

Introduces a basic Makefile, as discussed in #316.
Files previously residing in hugo/ are now kept in hugo-src and copied
as part of the build process, so that rm -rf hugo cleans everything.
The Makefile consists of a set of phony targets, each building a part
of the site.
Relevant targets:
- site: creates the site
- all: cleans output, checks validity of XML and creates the site
- serve: starts a web server on localhost:8000 to browse the site
- upload: rsyncs the site to the aclweb webserver
This means: `make all serve` will rebuild the site from scratch and start a webserver,
`make all upload` will rebuild the site and upload it to the official web server.
Comments welcome!

new Makefile, copy static files from other directory

---

Makefile

Now a complete rebuild should automatically triggered once the acl
data changes; make clean is now only needed if the software side
changes.

make: targets depend on xml&yaml files in data.

---

data/xml/N19.xml

This TACL paper (https://www.mitpressjournals.org/doi/full/10.1162/tacl_a_00254)
was inadvertently added to the NAACL proceedings.

removed TACL paper

---

data/xml/schema.rnc

Pretty trivial, but wanted to wait for #317 to land.
I am sure we could tighten the schema even more, i.e. create a doi
regexp.

schema: only positive integers for ids, year has to be a year.

---

Makefile
hugo/layouts/papers/list-entry.html
hugo/static/.htaccess

This adds an invisible link to papers with a `.pdf` extension, which should fix TPMS crawling of author pages.

added invisible PDF link (closes #377)

---

bin/normalize_anth.py
data/xml/L06.xml

L06.xml: restore fix to dotless i
#417 normalize_anth.py does contain code fixing dotless i with an accent.
latex_to_unicode.py mentions it as well.  What else needs to be fixed?

normalize_anth.py: find papers in nested volumes

---

bin/create_hugo_pages.py

This PR changes the canonical URL of volume pages to be their ID instead of a slug of their title.
This means that, for example, S12-1 would have the canonical URL:
+ `https://aclweb.org/anthology/volumes/S12-1/`
In addition, the current title slug is retained as an alias, and another alias is set for the logically equivalent `/papers/` URL, so the following two will both work & redirect to the canonical URL:
+ `https://aclweb.org/anthology/volumes/sem-2012-the-first-joint-conference-on-lexical-and-computational-semantics-volume-1-proceedings-of-the-main-conference-and-the-shared-task-and-volume-2-proceedings-of-the-sixth-international-workshop-on-semantic-evaluation-semeval-2012/`
+ `https://aclweb.org/anthology/papers/S/S12/S12-1/`

Change canonical URLs of volume pages (resolves #430)

---

bin/create_hugo_pages.py

Looks like I made a pretty nasty mistake when addressing #430 — the alias for the old volume URLs, unlike the main URL slug, apparently needs to be specified with absolute paths...
This will resolve #446.

Change volumes aliases to the correct URL slug (re #446)

---

data/xml/W89.xml
data/yaml/name_variants.yaml
data/yaml/sigs/sigparse.yaml

Ingestion of IWPT 1989. Closes #382. PDFs can be found [here](https://wwwtcs.inf.tu-dresden.de/~kilian/assets/W89-02.tar.gz). Just about 50% of the papers have abstracts. Thanks again to CMU Library for providing the scan.
If someone is keen on double-checking the spelling of authors and titles, this would not be a bad thing, as both the website as well as the OCR from which the information is derived contained errors. I did quite a few manual corrections, but there might be something I missed.

Ingestion of IWPT 1989

---

data/xml/D18.xml
data/xml/W19.xml

Added EMNLP 2018 tutorial abstracts from conf. webpage. One diff is 'fix' spell-error in T1 abstract (neual => neural).

added EMNLP 2018 tutorial abstracts

---

data/xml/D14.xml
data/xml/D16.xml
data/xml/D18.xml
data/xml/P16.xml
data/xml/W19.xml

Added EMNLP 2018 tutorial abstracts from conf. webpages. Minor spell-/formatting- errors are also fixed. 
Also, looks like tutorials were not part of EMNLP prior to 2014. So, I can't find any information about tutorials in EMNLP 2010-2013.

EMNLP 2014 and 2016 tutorial abstracts

---

hugo/config.toml
hugo/content/_index.md
hugo/layouts/_default/baseof.html
hugo/layouts/index.html

This PR removes the feedback banner from the top of every page, and adds a feedback button to the landing page sidebar like this:
Alternative suggestions are welcome, but I do think it's time to get rid of the top banner for ACL :)

Move feedback button to sidebar, remove banner

---

hugo/assets/css/_papers.scss

I confirmed that the spacing of paper lists is slightly off on some browsers/systems, as mentioned by @mjpost in https://github.com/acl-org/acl-anthology/pull/443#issuecomment-512897195. It looks similar for me on Chrome on Windows 10, for example.
Slightly increasing the minimum width should fix this and won't disturb the layout much on any system.

Slightly increase width of button row in paper lists

---

data/yaml/sigs/sigann.yaml
data/yaml/sigs/sigbiomed.yaml
data/yaml/sigs/sigedu.yaml
data/yaml/sigs/siglex.yaml
data/yaml/sigs/sigmorphon.yaml
data/yaml/sigs/sigrep.yaml
data/yaml/sigs/sigslav.yaml

Added missing SIGs.
What I'd really like is for this to be added as a new tag in the ACLPUB XML, so that it could be automatically ingested (https://github.com/acl-org/ACLPUB/issues/15).

ACL2019 workshop sigs

---

hugo/static/.htaccess

This redirects nested pages like
https://aclweb.org/anthology/papers/P/P19/P19-1013/
to their canonical `/`ed variants at
https://aclweb.org/anthology/P19-1013/
so as to get rid of duplicate pages in the search results.

redirect nested paper pages to canonical variant with /

---

.travis.yml
Makefile

Also checks whether the python version is new enough.  No more
handling the virtualenv by hand anymore.
Possible downside: it assumes that the system-wide python3 is the one
that should be used for building the site.  I don't think that this is
a real problem.

Use and update venv inside Makefile

---

.travis.yml
Makefile
hugo/layouts/partials/footer.html

This PR adds build time and github stamp to the footer of the main page.
Hugo has variables for this, but I spent an hour trying to get it to format dates correctly, and it also didn't seem to be able to compute git hashes.

Add build information to front page footer

---

bin/anthology/papers.py
hugo/layouts/papers/single.html

This adds open graph headers. One effect is that when Anthology papers are shared in locations such as Slack, a nice summary is displayed:

added open graph headers (closes #403)

---

hugo/static/.htaccess

Links to revisions (https://www.aclweb.org/anthology/D14-1096v2.pdf) were not being displayed. This fixes that and closes #554.
This is already live. If someone (@akoehn) can approve this and merge it before 8 PM EST tonight, I would appreciate it (that's when the site gets auto-rebuilt from master).

hotfix: revisions were not being displayed

---

bin/anthology/papers.py
bin/create_bibtex.py

This PR removes abstracts from volumes BibTeX files and from the complete Anthology export. I think this is the right thing to do and at least a compromise on #243. For example, it shaves about 25% of the size from the complete Anthology export.

remove abstracts from volume and anthology files

---

data/xml/L08.xml
data/xml/L10.xml
data/xml/L12.xml
data/xml/L14.xml
data/xml/L16.xml
data/xml/L18.xml

LREC 2008 currently has no metadata, so I went along and added it according to the official BibTeX entries on their website.
I also went through LREC 2010–2018 to make the spelling match their official metadata and, in a few cases, fix editor lists.
There seems to be no official BibTeX for LREC 2006 and older, so I didn't touch those.

Update LREC metadata

---

data/xml/P02.xml

[The PDF](https://aclweb.org/anthology/P02-1000.pdf) is in place. 
(2-page author index!)

scanned ACL 2002 frontmatter (#571)

---

data/xml/E12.xml

and remove incorrect fixed-case marking resulting from missing space.
space is present in PDF title.

E12-1009 title: "BothWorlds" -> "Both Worlds"

---

data/xml/D16.xml
data/xml/D18.xml
data/xml/W16.xml

Right now I have two ACL Anthology pages because my name shows up in the metadata in two different ways:
- John Lalor
- John P. Lalor
This pull request updates the metadata to replace "John Lalor" with "John P. Lalor" on a few files so that my papers all roll up to a single author file.

update metadata on John P. Lalor for consistency

---

data/xml/P10.xml

Paper title of P10-4004 is given as "GernEdiT: A Graphical Tool for GermaNet Development" in the PDF, but metadata and proceedings TOC give it as "GernEdiT - The GermaNet Editing Tool". This causes confusion with L10-1180, which is also titled "GernEdiT – The GermaNet Editing Tool". I therefore propose to use the PDF's title in the metadata.

Corrected paper title

---

data/xml/D19.xml

My name's capitalization in the metadata is different from the pdf/source of the paper ([https://www.aclweb.org/anthology/D19-1293](https://www.aclweb.org/anthology/D19-1293)).

Update D19.xml to fix author name for EMNLP paper

---

Makefile

Just noticed that I was running 0.55 instead of 0.58; this is my automated check for the future.  Confirmed that it work pre- and post-update of hugo :-)

Check for correct hugo version in the Makefile

---

.github/workflows/publish.yml

Just deletes the -v so we have shorter logs.

GH publish action: no verbose logging

---

hugo/layouts/volumes/single.html

This reflects the changes made to the paper templates earlier, see
commit 0c9ba6a8cc1e85d6a3dd14e01823f238ce306994.  Fixes #587 (now for
real, hopefully)

Use canonical URL in venues as URL instead PDF, link PDF at bottom

---

data/xml/D18.xml

Fixes #690. I am not sure how this happened, but the reason it was not fixed in #134 is that the demo abstracts were not missing.

fix incomplete abstracts in EMNLP 2018 demos

---

bin/anthology/papers.py

Fixes PDF links appearing (inherited from the volume) when the paper does not have an associated PDF.

Do not inherit 'pdf' from volume (fixes #698)

---

data/xml/W17.xml

Fixed name spelling (first commit) and removed redundant spacing (second commit).

Name fix spelling

---

data/xml/R19.xml

The main volume name is incorrect, and I missed this when I did the ingestion. I chose this new name for consistency with [past volumes](https://www.aclweb.org/anthology/venues/ranlp/), but have not yet confirmed with the volume editor that it is okay. However, I think we should adopt this variant right away since it would be good to have the correction in and this is clearly a step in the right direction.
I have also created a [rudimentary ingestion checklist](https://github.com/acl-org/acl-anthology/wiki/Ingestion-Checklist) to help me avoid overlooking this kind of mistake in the future.

corrected main volume book title

---

data/xml/Q18.xml

Reorders the text in the Anthology to match the PDFs and their previous order. (Note that this is a different order than the TACL IDs, to match how we had things in the past.)

Fix TACL/anthology out-of-sync (closes #723)

---

data/xml/N16.xml

@davidweichiang Any idea why the "LSTM" example wasn't caught by the heuristics?

fixed-case

---

bin/ingest.py
data/yaml/venues_mapping.yaml
hugo/content/info/contrib.md
hugo/static/.htaccess

I found a few small bugs in testing out the latest ingest under the new ID format: https://www.aclweb.org/anthology/events/ws-2020/
I expect a few more to show up, so don't merge yet. I will look at this more tonight.

New id fixes

---

hugo/content/faq/linking.md
hugo/content/info/contrib.md
hugo/static/.htaccess

Updated FAQ and other documentation with info on new ID format.
Also fixes bug that prevents *.bib, *.xml, etc being served for new IDs (e.g., https://www.aclweb.org/anthology/2020.iwclul-1.4.xml).

documentation updates for new ID format (plus bug fix)

---

data/xml/N19.xml

Somewhere along the line two versions of the video for [N19-1168](https://www.aclweb.org/anthology/N19-1168/) were uploaded - [one with the correct title](https://vimeo.com/361580764), and [one with 1169's title](https://vimeo.com/359681098). This left [N19-1169](https://www.aclweb.org/anthology/N19-1169/) linking to the wrong video (the latter) - this PR updates the link to the [correct one](https://vimeo.com/359678934).

Fix N19-1169 video link

---

data/xml/L08.xml
data/xml/O17.xml
data/xml/P16.xml
data/xml/R17.xml

These are all metadata errors.
(V.G.Vinod Vydiswaran also fits the pattern, but that appears to be intentional [judging by his homepage](http://www-personal.umich.edu/~vgvinodv/).)

Author initial + period missing space after

---

hugo/layouts/papers/list-entry-author.html
hugo/layouts/papers/list-entry.html

I've replaced periods in identifiers with double dashes so they work again with Bootstrap Collapse.

Fix abstract toggling for new-style IDs (fixes #813)

---

hugo/layouts/partials/footer.html

Footer year was static and out of date; use Huge date format to automate this range to always put copyright up until current year.

have hugo auto-update footer date range

---

bin/anthology/bibtex.py
bin/anthology/utils.py
bin/ingest.py
data/xml/2007.sigdial.xml

Adds a missing volume, contributed by Mikio Nakano. Includes a few changes to the scripts:
- Adds hashes to `ingest.py` (#819)
- Adjusts field names read in from ACLPUB "meta" file
- `compute_hash_from_file` convenience function

Ingest SIGDIAL 2007

---

data/xml/2020.acl.xml

Capital D in Out-of-Domain as in final PDF. Apologies for missing this in the submission form.
Reference: "Correcting Metadata" https://www.aclweb.org/anthology/info/corrections/

meta-data: capitalisation in title 2020.acl-main.778

---

data/xml/2020.acl.xml
data/xml/2020.alvr.xml
data/xml/2020.autosimtrans.xml
data/xml/2020.bea.xml
data/xml/2020.bionlp.xml
data/xml/2020.challengehml.xml
data/xml/2020.ecnlp.xml
data/xml/2020.fever.xml
data/xml/2020.figlang.xml
data/xml/2020.iwpt.xml
data/xml/2020.iwslt.xml
data/xml/2020.ngt.xml
data/xml/2020.nli.xml
data/xml/2020.nlp4convai.xml
data/xml/2020.nlpmc.xml
data/xml/2020.nuse.xml
data/xml/2020.repl4nlp.xml
data/xml/2020.sigmorphon.xml
data/xml/2020.socialnlp.xml
data/xml/2020.winlp.xml
hugo/static/.htaccess

* Adds full volume PDFs
* Fixes .htaccess redirect to load new-ID full volume PDFs
* Removes a pulled paper

ACL 2020 fixes (closes #893)

---

data/xml/2020.acl.xml

Fixed title to match the PDF -> "Probing Linguistic Features of Sentence-Level Representations in **Neural** Relation Extraction"

Correction to Anthology ID 2020.acl-main.140

---

data/xml/C80.xml

Added missing umlauts to paper title to match PDF.
Issue #961

Add missing umlauts to paper title

---

bin/fixedcase/README.md
bin/fixedcase/common.py

Stopped fixed-case tagging of "K" and "N" because it resulted in marking of expressions like "N-gram" and "K-means"
Issue: #959

Stopped fixed-case tagging of "K" and "N"

---

bin/tacl_cl_parser.py
data/xml/2020.tacl.xml

This brings TACL 2020 up to date.
Note that I found and fixed a bug in the ingestion: MIT Press does not provide files in page order so I had to change `bin/tacl_cl_parser.py` to explicitly sort incoming papers by page numbers. <strike>**This invalidates two assigned IDs**. I am thinking of just fixing the problem, but we may want to stick to the invariant that assigned IDs cannot be changed. In this case, I will keep the IDs, and change the order in the file.</strike>
**Update**: I'm not sure why I thought IDs were invalidated, but I've fixed that.
I also simplified the ingestion script. It now takes only the directory containing the MIT press unzipped archives, as documented. It infers the XML file path and updates it, skipping already-ingesting files (identified by DOI).

Ingest TACL 2020

---

Makefile

closes #815 (as discussed).
basedirs: create more directories that are needed
yaml, hugo_pages: depend on basedir instead of static (no rebuild on
static data changes)
hugo: depend on static (was transitive dependency before)

Makefile: depend on less to rebuild fewer items on changes

---

bin/anthology/papers.py
hugo/static/.htaccess

Papers with no PDF currently generate a faulty URL field (see image), partially because of the confusion between URL and PDFs (#997). This adds the "url" attribute when there is no `<url>` tag in the XML, fixing this display issue.

add "url" attrib

---

data/yaml/joint.yaml
data/yaml/sigs/signll.yaml

- Following policy of previous years, don't list CoNLL as joint with EMNLP. (As it stands Zotero infers a conference abbreviation of "CoNLL-EMNLP", which is incorrect.)
- List CoNLL 2020 under SIGNLL

CoNLL 2020 venue

---

data/xml/2020.nlposs.xml
data/yaml/name_variants.yaml

Hi!
My name was incorrectly input when we were producing the proceedings, and a duplicate author page was created for me.
- Canonical (with the middle initial): https://www.aclweb.org/anthology/people/n/nelson-f-liu/
- Duplicate (without the middle initial): https://www.aclweb.org/anthology/people/n/nelson-liu/
Following prior PRs, I tried to fix (1) the metadata of the NLP-OSS proceedings and (2) add a variant for my name. Let me know if there's anything else I need to do.
Thanks in advance!

Fix name metadata for Proc. of NLP-OSS 2020, add a name variant

---

data/xml/2020.emnlp.xml

Fix metadata for EMNLP 2020 Demo "Transformers" (fixing author order and typo) to make it consistent with the [PDF version](https://arxiv.org/pdf/1910.03771). No PDF revision needed. We have already contacted EMNLP 2020 PC chairs, demo chairs, and publication chairs and they direct us to fix it here. @mjpost

Fix Metadata for 2020.emnlp-demos.6

---

data/xml/2020.emnlp.xml

This paper was withdrawn prior to the conference and was not presented there, so should not have been included with the proceedings.

removed 2020.emnlp-main.401

---

data/xml/2020.amta.xml

Hi!
As instructed by @mjpost, I am making a PR to correct the author list for the AMTA 2020 user track paper No. 25. The author list is in the same order as in the published PDF of the paper.
Thanks!
Best regards,
Mārcis

Fixed author list for AMTA 2020 user track paper No. 25.

---

bin/anthology/index.py
data/xml/2015.eamt.xml
data/xml/2018.jeptalnrecital.xml
data/xml/2020.privatenlp.xml
data/xml/C10.xml
data/xml/L14.xml
data/xml/W11.xml
data/xml/W14.xml
data/xml/W15.xml
data/xml/W18.xml
data/xml/Y14.xml
data/xml/Y15.xml
data/xml/Y17.xml
data/xml/Y18.xml
data/yaml/name_variants.yaml

Slugify name

---

data/xml/W18.xml
data/xml/W19.xml

Amusingly, for some strange reason, in both of my two publications that have the language "Sámi" in the title, my first name has been set to "Sámi" instead of "Sami".

fix author first name in W18-02 and W19-03

---

data/yaml/venues.yaml
hugo/content/info/contrib.md

I noticed that some workshop names were entered into `venues.yaml` with specific event names ("The 3rd Workshop on ..." instead of just "Workshop on ..."). This works while there's only a single event belonging to that venue, but it's technically wrong and has the potential to break in the future (when we add another event to the same venue).
@mjpost Maybe you also want to make a note about this somewhere for future ingestions?

Venues should not refer to specific events

---

bin/anthology/index.py
bin/create_bibtex.py

Uppercase 'NONE' creates a problem during the YAML files generation step.
The problem arises in **OSX**.
Let me explain the problem.
After cloning the repository, I run the below commands:
1. make venv/bin/activate
2. make build/.basedirs
3. make build/.yaml
build/.yaml target produces people YAML files in build/data/people. As I understood, Anthology groups author data according to their first letter, and there are some papers without author info such as 'O09-2000' so you assign 'NONE' author id to these papers. OSX (HPS+ file system) does not support a case-sensitive file system so n.yaml and N.yaml files are the same. During the 'make build/.yaml' step, firstly, author names starting with 'n' produces the n.yaml file, finally, authors with NONE id (does not produces N.yaml) overrides …

Bugfix : Uppercase 'NONE' creates a problem during the YAML files generation

---

.github/workflows/check-build.yml
.github/workflows/publish.yml

we previously used ubuntu-latest, which now changed and broke stuff.
ubuntu comes with python 3.8 by default, no need to install it anymore.

CI/CD: explicitly use ubuntu 20.04

---

data/xml/2020.tlt.xml

Added links to TLT 2020 videos. Source: https://tlt2020.phil.hhu.de/schedule/

TLT 2020 videos

---

data/xml/N19.xml

The video has the wrong audio track and is therefore not comprehensible.

Remove video link from N19-1116 upon first author's request

---

bin/create_bibtex.py

This generates (but doesn't advertise) the full bib file, uncompressed. The main motivation is that this allows direct import into Overleaf (which doesn't support compressed files).

Add uncompressed full bib

---

data/xml/2000.amta.xml
data/xml/2002.jeptalnrecital.xml

- included page numbers
- wanted to include abstracts, but I do not think Springer allows this, what do you think @mjpost ?
Maybe it is better to use the naming convention of AMTA 2020, i.e. using Volume 1 / Volume 2 / ... for different tracks:
* Proceedings of the 14th Conference of the Association for Machine Translation in the Americas (Volume 1: Research Track) 16 papers
* Proceedings of the 14th Conference of the Association for Machine Translation in the Americas (Volume 2: User Track) 29 papers
?
Also, note that I included the pre-conference workshop as _Proceedings of the Workshop on Machine translation in practice: from old guard to new guard_, even though this was **published separately from the proceedings of the main conference**. Let me know if you agree.

ingested amta 2000

---

data/yaml/venues.yaml

A few venues list their acronym in brackets as part of the name field, e.g. "International Conference on Computational Linguistics (COLING)". However, this information is already configured in the acronym field. On the venue's page this results in a duplication: "International Conference on Computational Linguistics (COLING) (COLING)"
This pull request removes the acronyms from the end of name fields.

Remove acronyms from venue names

---

bin/ingest.py
data/xml/2021.motra.xml
data/xml/2021.nlp4call.xml
data/xml/2021.nodalida.xml

The submitters submitted a dummy front matter. This replaces it, and adds the full book proceedings.

Fixed dummy frontmatter

---

.github/workflows/preview.yml
Makefile
bin/aclanthology.org/README
bin/aclanthology.org/remove-previews.sh

Per @akoehn's suggestion, this PR moves previews from their old location at `https://aclanthlogy.org/previews/{branch}` to a new top-level location at `https://preview.aclanthology.org/{branch}`. The main benefits are:
* Previews are no longer nested within the main site, simplifying syncing and cleanup
* The word "preview" in the domain increases the visibility of the nature of the preview

Top level previews

---

bin/anthology/data.py

Currently the doi links are all http. I think they should be https for better security and privacy.

https doi url prefix instead of http

---

data/xml/2021.calcs.xml

The [entry](https://www.aclweb.org/anthology/2021.calcs-1.0/) for the 2021 Code-Switching Workshop, held at NAACL, is missing the name of one of the workshop organizers. Both the [workshop website](https://code-switching.github.io/2021) and the [PDF](https://www.aclweb.org/anthology/2021.calcs-1.0.pdf) uploaded along with the entry have the name (check Page 5 in the PDF).
I've made a PR, adding the missing name to the entry.

Update 2021 CALCS WS Organizer Information

---

bin/anthology/anthology.py
bin/anthology/index.py
bin/anthology/volumes.py

Fixes #1405.
This means some people [can have empty paper listings](https://preview.aclanthology.org/fix-dummy-frontmatter/people/k/kathryn-b-taylor/) when they only ever appear as editors of proceedings without front matter.
A better way would be to make the code keep a separate index for volume editors and generate entries from that, but that also adds more complexity to the code – I could look into that if you think it's worth it.

Refactor "dummy frontmatter" (fixes #1405)

---

data/xml/2021.woah.xml

The title in the pdf of the paper 2021.woah-1.17 and in the meta data are not in sync (my fault).
Here is the link to the pdf, where the title is "Data Integration for Toxic Comment Classification: Making More Than 40 Datasets Easily Accessible in One Unified Format". I updated the meta data entry accordingly.
https://aclanthology.org/2021.woah-1.17.pdf

Update title of 2021.woah-1.17 according to pdf

---

data/xml/2021.acl.xml
data/xml/E14.xml
data/xml/L14.xml

Add three public video links, including to an ACL 2021 talk where Underline don't have the correct video in place but do have a working Anthology link.

add three video links

---

data/xml/2018.gwc.xml

Hello,
This is a fix for the metadata for a paper I have authored. There was a typo in the first name and an incorrect split of first and last name. With this fix it now agrees with the PDF: [https://aclanthology.org/2018.gwc-1.13.pdf](https://aclanthology.org/2018.gwc-1.13.pdf)
Thank you very much!

Correction of metadata - typo in author's name

---

bin/create_hugo_pages.py
hugo/config.toml

Removes the outdated alias under `/papers` that is still created for volumes, e.g.
- https://aclanthology.org/papers/2021.eacl/
- https://aclanthology.org/papers/2021.eacl/2021.eacl-main/
Closes #1087

Remove nested alias for volumes

---

data/xml/2019.gwc.xml

Corrected the order of the authors to match that given in both the paper and the proceedings ToC. I also changed the title capitalisation to match that in the paper (although the current capitalisation can be found in the proceedings ToC).

Correct author order and title capitalisation

---

data/xml/2021.acl.xml
data/xml/2021.case.xml
data/xml/2021.findings.xml
data/xml/2021.gem.xml

Reviewing notes were inadvertently submitted for ingestion as attachments. This removes them. (I have already 404'd the attachments themselves).

Removed links to reviewing notes

---

bin/anthology/volumes.py

Most volumes currently don't show their URL, which is a bug. This fixes that.
+ Before: https://aclanthology.org/volumes/2020.tacl-1/
+ After: https://preview.aclanthology.org/show-volume-urls/volumes/2020.tacl-1/ *(once generated)*

Show URL field for volumes

---

Makefile

this way you get a clean start, e.g. with a new version of python
make all does not make clean (in order to avoid reinstalling libs each time)
closes #826

"make clean" now removes venv directory

---

data/xml/2011.iwslt.xml

See https://aclanthology.org/www.mt-archive.info/10/IWSLT-2011-TOC.htm for original.
* I have called the volume with keynotes `keynotes` instead of `plenaries`. What do you think? Should I change previous editions to `keynotes` as well, since they only include keynotes?
* For the Evaluation Campaign / Papers volume split I have used this website: https://www.isca-speech.org/archive/iwslt_11/

ingested iwslt 2011

---

hugo/content/info/contrib.md

People should really follow the link to the ACLPUB documentation here, which also
contains detailed EasyChair instructions. Clicking on the easy2acl link risks
leading you to believe you have all the information you need when you don't.

Removed redundant, potentially misleading info

---

data/xml/2021.eval4nlp.xml

I am one of the authors of the paper "SeqScore: Addressing Barriers to Reproducible Named Entity Recognition Evaluation", 2021.eval4nlp-1.5. The software attachment in the anthology is not from our paper and appears to be another copy of the software from paper 2021.eval4nlp-1.9. Our paper should not have any software attached to it.

Remove incorrect software attachment for 2021.eval4nlp-1.5

---

data/yaml/joint.yaml

- add CRAC 2020/2021 under crac
- fix spelling of CRAC 2021 under EMNLP 2021 (dash -> dot); also for EANCS.
Fixes #1633

Fix CRAC 2020/2021 listings in joint.yaml

---

data/xml/D19.xml

**Description of changes**
The previous meta data in xml is not consistent with the author list in the PDF file. Correct the authors according to the PDF's author list.

Correction to Anthology ID D19-1074 metadata

---

data/xml/2021.textgraphs.xml

The order of authors in the published PDF does not match the one listed on ACL Anthology: https://aclanthology.org/2021.textgraphs-1.17/. This pull request fixes this inconsistency by sticking to the correct order in the PDF.

Fix the order of authors in 2021.textgraphs-1.17

---

.github/workflows/paperswithcode.yml

The current Papers-with-Code workflow doesn't work since **our master branch is protected** (by status checks + reviewer approval). There currently seems to be no way for workflows to bypass this, [unless we also allow all repo admins to bypass this](https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/34), which @mjpost would like to avoid.
This PR will therefore change the workflow as follows:
- Push changes to a fork owned by the new [acl-pwc-bot](https://github.com/acl-pwc-bot/) account, and **create a pull request** from that.
The separate acl-pwc-bot is used so that the PR automatically triggers the build checks, which are required for merging. A pull request created by the workflow itself would _not_ trigger other workflows, such as the build …

Make Papers-with-Code workflow use acl-pwc-bot

---

.github/workflows/paperswithcode-automerge.yml

The documentation led me to believe that we can't automatically merge PRs to a protected branch, but [testing on my personal fork](https://github.com/mbollmann/acl-anthology/pull/12) suggests that it might work after all.
This action would:
- Trigger whenever a build check is completed.
- When the build check belongs to a PR by acl-pwc-bot, attempt to automatically squash-merge it.
- Merging uses @acl-pwc-bot's credentials, since merging via the default token wouldn't trigger our deployment/publish workflow. **This would require inviting @acl-pwc-bot as a collaborator to our repo.** (@mjpost)

Add workflow to automatically merge acl-pwc-bot's PRs

---

.github/workflows/paperswithcode-automerge.yml

Somehow I put in the wrong event trigger (`check_suite` instead of `workflow_run`) when copying this workflow over from my personal fork... This fixes that.

Fix pwc-automerge event trigger

---

.github/workflows/paperswithcode.yml

The action to auto-merge PwC changes now triggers, but [doesn't actually attempt to merge anything](https://github.com/acl-org/acl-anthology/actions/runs/1503675588). I believe that's because the commit in the [automated pull request](https://github.com/acl-org/acl-anthology/pull/1684) is currently attributed to Matt Post, and the automerge action by default doesn't attempt the merge if anyone except the designated account (here: acl-pwc-bot) made changes within it. That's a security measure, and I feel it's good to leave it activated.
This PR changes the workflow so that:
- Commits in the PwC action should now appear as authored by the acl-pwc-bot
- The PR is now triggered daily whenever there are changes (since we–hopefully–don't need to manually approve it)
- The body of the PR is a …

Update Papers with Code action

---

.github/workflows/paperswithcode.yml

This PR changes the Papers-with-Code action to push to a local branch named `automated/update-pwc-metadata`. Currently, it pushes to a fork of our repo, which [is the likely reason for the auto-merge action to not see the pull request data](https://github.com/acl-org/acl-anthology/pull/1686#issuecomment-980065627).
@mjpost Does @acl-pwc-bot have permission to push commits to our repo? I believe you said you gave the bot more restricted permissions initially. Either way, this PR shouldn't merged unless we (want to) give the bot those permissions.

Make acl-pwc-bot push to local branch

---

data/xml/2021.eacl.xml

Fixing the formatting for the name of the software library. The name should begin with an upper-case letter, i.e. `Nisaba` rather than `nisaba`.

Fixed casing for 2021.eacl-main.226

---

.github/workflows/paperswithcode.yml

Per private discussion, we decided to change the PWC merges to once a week. The motivation was to have cleaner commit histories (we are currently seeing a commit every day or two, the majority of all commits) and the justification is that the data is not urgent.

Change PWC merge frequency to 1x / week

---

Makefile
README.md

We're using `functools.cached_property` which requires Python 3.8, but the README and Makefile still list 3.7.
I noticed this by running [vermin](https://github.com/netromdk/vermin). This could also be added to the build check to ensure we're staying compatible with a given Python version, though I'm not sure how useful/needed that is.

Bump to Python 3.8 in README and Makefile

---

bin/anthology/papers.py
data/xml/2017.iwslt.xml

See [here](https://workshop2017.iwslt.org/index.php) for the website and [here](https://workshop2017.iwslt.org/downloads/iwslt2017_proceeding_v2.pdf) for the proceedings PDF.
- The `bin/write_bibkeys_to_xml.py` script failed with the following error: `ERROR    Paper 2017.iwslt-1.1 has bibkey that is not unique (False)!` (for all papers). To solve this, I changed `self._bibkey` init value to `None` instead of `False` in `bin/anthology/papers.py`, based on a comment from @mbollmann in #1833. I do not think this creates new bugs, but I'm not sure.
- I ran into issues related to `pdftk`. It failed to split the PDF. The error is similar to [this one](https://stackoverflow.com/questions/36613976/pdftk-throws-a-java-exception-when-attempting-to-use-fill-form-function). I tried to debug it and …

ingested iwslt 2017

---

data/xml/W19.xml

The author ordering for paper W19-1102 was inconsistent with the underlying PDF. This change fixes that ordering, and re-names the generated citation ID accordingly.

Fixed author ordering for W19-1102 to reflect PDF content

---

data/xml/2020.sigdial.xml

Hi,
I've seen that in the ACL Anthology, there is a wrong youtube link from my demo paper submitted to SIGdial 2020:
https://aclanthology.org/2020.sigdial-1.6/
I've changed the link here in the XML file and hope this is the right place to edit.
Best,
Thilo

Fixed the YouTube-URL of the Retico demo paper

---

data/xml/C90.xml

Classic m-looks-like-r-followed-by-n goof in the OCR of the proceedings, looks like.

Correct OCR error in author name Kemighan → Kernighan

---

data/xml/2022.acl.xml

My last name's particle's initial should not be uppercased: De Lhoneux --> de Lhoneux

lowercase last name initial

---

data/xml/2022.csrr.xml

Link: https://aclanthology.org/2022.csrr-1.0/
The list of authors should be: Antoine Bosselut, Xiang Li, Bill Yuchen Lin, Vered Shwartz, Bodhisattwa Prasad Majumder, Yash Kumar Lal, Rachel Rudinger, Xiang Ren, Niket Tandon and Vilém Zouhar.
This PR makes the necessary changes for #1932

fix proceedings author metadata

---

data/xml/2022.acl.xml

Name change from Rakesh Menon to Rakesh R. Menon in ACL 2022 paper.
Changed file: [data/xml/2022.acl.xml](https://github.com/acl-org/acl-anthology/blob/master/data/xml/2022.acl.xml)

Name correction for 2022.acl-long.451

---

data/xml/2022.iwslt.xml

Adds missing author for 2022.iwslt.20 in metadata
Corresponding authors: [wangmh1994@gmail.com](wangmh1994@gmail.com), [liyinglu@huawei.com](liyinglu@huawei.com)

Metadata correction for 2022.iwslt-1.20

---

data/xml/2022.acl.xml

A. Seza --> Correct name now displayed on the file for paper acl-long-273

Name correction for 2022.acl-long.273

---

data/xml/2022.computel.xml

Colon was missing from the title, which was present in the OpenReview title.

Update metadata for 2022.computel-1.15: fix title

---

data/xml/2022.acl.xml

Name correction "Alham Aji" -> "Alham Fikri Aji"

Metadata update for 2022.acl-long.500

---

data/xml/2022.acl.xml

One author Baorong Huang is missing from the citation information for https://aclanthology.org/2022.acl-long.91/. There are three authors for this paper, as indicated in the PDF file https://aclanthology.org/2022.acl-long.91.pdf.

Add missing author to 2022.acl-long.91

---

.github/workflows/publish.yml

We occasionally do multiple merges at once, which then all publish concurrently and cause rsync errors. This feature only allows one to run at a time.
[doc](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)

Preview lock

---

data/xml/2022.eamt.xml

The author of [paper 7](https://aclanthology.org/2022.eamt-1.7) contacted us with a request to change the title to a more common format.
Changes the title from 
`Passing Parser Uncertainty to the Transformer. Labeled Dependency Distributions for Neural Machine Translation.`
to
`Passing Parser Uncertainty to the Transformer: Labeled Dependency Distributions for Neural Machine Translation`
I assume that the corresponding bibtex will be updated accordingly?

Update title of 2022.eamt-1.7

---

data/xml/2022.findings.xml

I fixed the name of the first author of the paper with an ID "2022.findings-naacl.156".
The name has changed from "M.j Jang" to "Myeongjun Jang".

Name correction to 2022.findings-naacl.156 (closes #2024)

---

data/xml/2022.woah.xml

Hello!
Issue:
WOAH2022 paper 24 has a different title in the pdf file.
[Metadata](https://aclanthology.org/2022.woah-1.24/): **HATE-ITA: New Baselines for Hate Speech Detection in Italian**
[PDF](https://aclanthology.org/2022.woah-1.24.pdf): **HATE-ITA: Hate Speech Detection in Italian Social Media Text**
This PR:
I have modified the metadata so that the title corresponds to the one in the paper (**HATE-ITA: Hate Speech Detection in Italian Social Media Text**)
Thank you!

metadata fix for paper 2022.woah-1.24

---

data/xml/2022.sigtyp.xml

SIGTYP 2022: Fixed typo in one paper's title.

---

Makefile

The old logic saw 3.10 as smaller than 3.8, hugo changed its version
output string.

Recognize python 3.10 and newer hugo versions correctly

---

data/xml/2022.acl.xml
data/xml/2022.naacl.xml

This PR corrects the metadata for two papers to add my middle initial. The middle initial is present in the PDFs:
- https://aclanthology.org/2022.naacl-main.338/ vs. https://aclanthology.org/2022.naacl-main.338.pdf
- https://aclanthology.org/2022.acl-long.122/ vs. https://aclanthology.org/2022.acl-long.122.pdf

Metadata correction - Adding missing middle initial for Jonathan K. Kummerfeld

---

data/xml/W19.xml
data/yaml/name_variants.yaml

updated author ids of three papers in `data/xml/W19.xml` in order to merge two author pages: the [Yang Janet Liu author page](https://aclanthology.org/people/y/yang-janet-liu/) is kept and [this one](https://aclanthology.org/people/y/yang-liu-georgetown/) should be gone. This PR was created to follow up on the corresponding Github Issue #2063.

merged two author pages of Yang Janet Liu

---

data/xml/W16.xml

Trivial change in casing: "python" -> "Python".

Fixed casing in gorman-2016-pynini (SIGFSM).

---

data/xml/2017.mtsummit.xml

Ingested mt-summit 2017. See [here](http://aamt.info/app-def/S-102/mtsummit/2017/wp-content/uploads/sites/2/2017/09/MTSummitXVI_ResearchTrack.pdf) and [here](http://aamt.info/app-def/S-102/mtsummit/2017/wp-content/uploads/sites/2/2017/09/MTSummitXVI_UserTrack_printer_friendly_version.pdf) for the original proceedings PDFs, consisting of two volumes.

ingested mt-summit 2017

---

data/xml/2021.sigmorphon.xml

The titles of the following three paper do not have protected cases (with the proper fixed-case tags):
2021.sigmorphon-1.25
2021.sigmorphon-1.27
2021.sigmorphon-1.29
This PR adds that protection.
Closes #2124

Fix casing in SIGMORPHON 2021's papers

---

data/xml/2020.acl.xml
data/xml/2020.emnlp.xml
data/xml/2020.figlang.xml
data/xml/2020.sigmorphon.xml
data/xml/2021.naacl.xml
data/xml/D19.xml
data/yaml/name_variants.yaml

Change name metadata for Rowan Hall Maudslay:
First name 'Rowan' surname 'Hall Maudslay' -> First name 'Rowan Hall' surname 'Maudslay'
Still matches PDFs etc.
Discussed this with Matt Post over email way back in March, and he said to create a PR, but I only just got round to it. I think I've changed it in all the necessary places (conferences XMLs, and added line to name_variants.yaml)

Author name metadata alteration

---

data/xml/2022.lrec.xml

Changing the Title in the metadata for ACL Anthology ID 2022.lrec-1.442 to make it consistent with the PDF: 
Current title: "TUSC: Emotion Word Usage in Tweets from US and Canada"
Updated title: "Tweet Emotion Dynamics: Emotion Word Usage in Tweets from US and Canada"

modify metada for 2022.lrec-1.442: change of title consistent with PDF

---

data/xml/2022.lrec.xml

Updated 2022.lrec-1.63 Metadata - Provided Missing Author Names and Corrected Wrong Author Names Arrangement (Consistent with Author Names and Arrangement in the Paper)

Add authors to 2022.lrec-1.63

---

data/xml/2022.naacl.xml

* Added videos for NAACL 2022.
I only pushed NAACL for now but I have also created (missing) video links for the following proceedings:
modified:   data/xml/2014.lilt.xml
modified:   data/xml/2020.cl.xml
modified:   data/xml/2020.tacl.xml
modified:   data/xml/2021.acl.xml
modified:   data/xml/2021.blackboxnlp.xml
modified:   data/xml/2021.calcs.xml
modified:   data/xml/2021.case.xml
modified:   data/xml/2021.cl.xml
modified:   data/xml/2021.codi.xml
modified:   data/xml/2021.conll.xml
modified:   data/xml/2021.crac.xml
modified:   data/xml/2021.dialdoc.xml
modified:   data/xml/2021.eacl.xml
modified:   data/xml/2021.econlp.xml
modified:   data/xml/2021.emnlp.xml
modified:   data/xml/2021.eval4nlp.xml
modified:   data/xml/2021.fever.xml
modified:   data/xml/2021.findings.xml
modified: …

Adding NAACL main conference videos

---

bin/create_hugo_pages.py

os.mkdir does not do nested directories, causing the script to fail. This uses os.makedirs() instead. First proper pull request. Fingers crossed.

makedirs instead of mkdir

---

data/xml/2022.dclrl.xml

Fixes spelling of my last name, Sälevä, as documented in #2201.
Ping @ConstantineLignos  🙂

Fix spelling in error in last name

---

data/xml/2022.acl.xml

Fixed first author's name in this paper: [Investigating Failures of Automatic Translation in the Case of Unambiguous Gender](https://aclanthology.org/2022.acl-long.243.pdf)
Anthology ID: 2022.acl-long.243
First author name is now inline with PDF.

Author name correction ID: 2022.acl-long.243

---

data/xml/2020.challengehml.xml
data/xml/2021.acl.xml
data/xml/2021.emnlp.xml
data/xml/2021.mwe.xml
data/xml/2021.spnlp.xml

Some papers have duplicate videos listed (e.g. [here](https://aclanthology.org/2021.acl-long.134/)). This PR removes those.
Code for doing this is [here](https://gist.github.com/GuyAglionby/93c1d6af00e45a802ef3c49f40decfaa). There is some hacky stuff there for ensuring that whitespace stays consistent, but I made sure that only lines with a video tag were changed.
```
➜  acl-anthology git:(guyaglionby-remove-dupe-videos) git diff a615ffe~ a615ffe -U0 | grep '^[+-]' | grep -Ev '^(--- a/|\+\+\+ b/)' | grep -v video | wc -l
0
```

Remove duplicate videos for papers

---

data/xml/2022.lrec.xml

Fix casing: "nigerian" -> "Nigerian"

Fix casing in the title of muhammad-etal-2022-naijasenti

---

data/xml/2016.amta.xml
data/xml/2020.iwclul.xml
data/xml/2020.vardial.xml
data/xml/2021.iwclul.xml
data/xml/2021.nodalida.xml
data/xml/2021.vardial.xml
data/xml/2021.wmt.xml
data/xml/L06.xml
data/xml/L18.xml
data/xml/W11.xml
data/xml/W14.xml
data/xml/W17.xml
data/xml/W18.xml
data/xml/W19.xml

These words have already been added to `bin/fixedcase/truelist`.

Fixed-case treatment for "Uralic", "Germanic" and "Yandex".

---

data/xml/W19.xml
data/yaml/sigs/sigsem.yaml

Linked from SIGSEM page, also corrected venue for 2019.

Links for CSTFRS

---

data/xml/2022.nejlt.xml

Author had accidentally delisted a few authors in an issue export - adding these manually

Re-add authors for 2022.nejlt-1.6 delisted in OJS

---

data/xml/2022.nejlt.xml

Author metadata was out of sync with paper title in this article, amended the relevant line

amend title metadata in 2022.nejlt-1.4

---

bin/fixedcase/truelist
data/xml/2009.freeopmt.xml
data/xml/2020.vardial.xml
data/xml/2021.konvens.xml

Hi! I'd like to add {N}ynorsk and {L}ow {S}axon to the list of words with fixed capitalization. 
I updated the list of capitalized words and edited the title metadata for [2009.freeopmt-1.7](https://aclanthology.org/2009.freeopmt-1.7/), [2020.vardial-1.3](https://aclanthology.org/2020.vardial-1.3/) and [2021.konvens-1.25](https://aclanthology.org/2021.konvens-1.25/) accordingly, but wasn't able to locate the metadata file for [W17-0201](https://aclanthology.org/W17-0201/).

Use fixed case for Nynorsk and Low Saxon

---

data/xml/2011.tal.xml

- Manual reformatting of booktitle to get homogenous formats across tal volumes (cf. #2431)
- added frontmatter blocks for issues 2 and 3, cf. the frontmatter block for issue 1 was added but not for 2 and 3
- modification of bibkey of frontmatter to avoid getting the same bibkey for the 3 issues of the 2011 volume

booktitle formatting + added frontmatter blocks for issues 2 and 3

---

data/xml/2021.eacl.xml

As usual, "Indic" was lowercase.

Fixed casing for `kunchukuttan-etal-2021-large`

---

data/xml/2018.tal.xml

Same modifications as #2464 but for 2018.tal volume
This aims at having homogenous booktitle formatting for 2011.tal, 2018.tal, and the pending volumes 2017, 2019, 2020 and 2021,
cf. https://preview.aclanthology.org/continued-tal-ingestion/venues/tal/ and #2431

2018.tal : booktitle formatting + added frontmatter for issues 2 and 3

---

bin/fixedcase/truelist
data/xml/2019.gwc.xml
data/xml/2022.eamt.xml
data/xml/2022.lrec.xml
data/xml/2022.sigul.xml
data/xml/2022.slpat.xml
data/xml/W17.xml

Hi again! Similarly to my previous PR (#2451), I would like to request updates to the capitalization list, this time for {A}lemannic and {S}tandard {G}erman (analogously to _Standard Estonian_, _Standard Malay_, etc., which are already in `fixedcase/truelist`). This affects the following papers (whose metadata I've edited accordingly): [2022.sigul-1.17](https://aclanthology.org/2022.sigul-1.17/), [2022.lrec-1.347](https://aclanthology.org/2022.lrec-1.347/), [2022.eamt-1.40](https://aclanthology.org/2022.eamt-1.40/), [2022.slpat-1.5](https://aclanthology.org/2022.slpat-1.5/), [2019.gwc-1.4](https://aclanthology.org/2019.gwc-1.4/).
(I also fixed the metadata for {N}ynorsk in the title for [W17-0201](https://aclanthology.org/W17-0201/), which I didn't do in my previous PR.)

Fixed capitalization (Alemannic, Standard German, Nynorsk)

---

data/xml/2021.nlp4posimpact.xml
data/yaml/venues/nlp4posimpact.yaml

Removes duplicate venue, keeping the shorter and more recent acronym.

Merge NLP4PosImpact with NLP4PI, fixes #2482

---

Makefile

Fixes a small bug in the Makefile: the virtual environment needs to be activated before checking if libyaml bindings are installed.
(I got the warning despite having all the dependencies installed, because there was no `yaml` module in my global environment.)

Activate venv before checking for libyaml

---

bin/ingest_pwc.py

In the file: ingest_pwc.py, a request is made without a timeout parameter. The requests.get method in Python does not use any default timeout value and should be explicitly set. Otherwise, if the recipient server is unavailable to service the request, the application making the request may stall indefinitely.  
What should be the timeout value? A good practice is to set it under 500ms. This PR proposes the value to be 400ms. However, this may vary depending on the use case. More information is available in: https://docs.python-requests.org/en/latest/user/advanced/#timeouts

Adding a timeout parameter to the HTTP request

---

hugo/layouts/_default/baseof.html

Uses the same mechanism as 9c7eed2 to include a `<meta name="robots" content="noindex, nofollow">` tag on every page if the build is for a preview branch.
I wonder if we should also additionally have a `robots.txt` that we push to the server in the `preview` target of the Makefile?

Don't index preview builds (closes #2425)

---

.github/workflows/check-build.yml
.github/workflows/paperswithcode.yml
.github/workflows/preview.yml
.github/workflows/publish.yml

1. Updates `actions/checkout` to `@v3` because older versions are raising a deprecation warning due to Node.js 12.
2. Replaces `::set-output` commands because [they are deprecated and will start failing on June 1st, 2023](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
3. Adds a check if we're in the `acl-org/acl-anthology` repo to the `preview` and `publish` workflows, which will stop Github from attempting to run them in forks of this repo (which fails, but is annoying).

Update Github Workflows

---

data/xml/2023.loresmt.xml

Corrections to the metadata for missing authors and author information from the PDF that shows up on anthology. Only the first 10 authors shows up on Anthology, this PR includes the rest. 
https://aclanthology.org/2023.loresmt-1.9/

Correction to 2023 LoResMT Submission 1.9

---

bin/anthology/utils.py

Reduces instantiation time from 9.005s to 8.480s on my system, should be functionally equivalent for our purposes, and is the fastest version I could think of as tested with pyperf:
```bash
$ pyperf timeit --setup 'from urllib.parse import urlparse' 'bool(urlparse("https://foobar.com/badabing.pdf").netloc)' 
.....................  
Mean +- std dev: 600 ns +- 6 ns
$ pyperf timeit '"https://foobar.com/badabing.pdf".startswith("http")' 
.....................  
Mean +- std dev: 40.0 ns +- 1.7 ns
$ pyperf timeit '"://" in "https://foobar.com/badabing.pdf"'
.....................  
Mean +- std dev: 13.5 ns +- 0.1 ns
```

Small performance improvement: Switch urllib with simpler check

---

bin/fixedcase/truelist
data/xml/2020.lt4hala.xml
data/xml/W11.xml

`Voynich` upper-cased for all instances found. Also updated the true-list.

Voynich upper-cased

---

data/xml/schema.rnc

Tiny change that disallows `<ISBN>` in the XML in favor of `<isbn>`.
Zero instances of the upper-case version currently exist in our XML, so there's no good reason to keep this potential for inconsistency around.

Remove upper-case ISBN from XML schema

---

hugo/config.toml
hugo/content/info/contrib.md
pyproject.toml

It seems that we have been deleting a huge HTML table with deadlines since we upgraded past hugo 0.60.
https://aclanthology.org/info/contrib/
This PR will also include other doc updates.

Restore contrib table; update documentation

---

hugo/layouts/sitemap.xml

Re #2611 and #2605, and based on an error I'm seeing in the Google Search Console, the `<PageMap>` tag in the sitemap needs to [declare its XML namespace](https://developers.google.com/custom-search/docs/structured_data#addtositemap).

Add namespace to PageMap in sitemap

---

data/xml/2023.acl.xml

Anthology id: 2023.acl-long.314
Corrects the name and affiliation of my long paper accepted to conference proceedings of ACL.
Apologies, I forgot to add my second name (which I use in academic contexts to distinguish my otherwise rather common German name) when maintaining my profile Softconf, where I believe this issue ultimately stems from. This should also resolve two different authors on ACL Anthology (Fabian David Schmidt vs Fabian Schmidt) and unify Google Scholar indexing. I hope to fix is in the right place.
Thanks in advance!

Fix author name & affiliation in 2023.acl-long.314

---

data/xml/2022.amta.xml
data/xml/2023.clinicalnlp.xml
data/xml/O06.xml
data/xml/O08.xml
data/xml/O09.xml
data/xml/O93.xml
data/xml/O94.xml
data/xml/O95.xml
data/xml/O97.xml
data/xml/schema.rnc
data/yaml/venues/iwclul.yaml
data/yaml/venues/konvens.yaml

- Enforce that `<last>` name cannot be empty
- Fix instances of empty `<last>` name tags
- Enforce that `<first>` and `<last>` must start/end with non-whitespace character
- Remove two spurious "joint" keys from venue YAML files
Closes #2725

Data fixes: first/last name tags (in XML), joint key (in YAML)

---

data/xml/2023.ccl.xml

**Fixed the problem of spelling error of the author's name.**
**The metadata currently displayed on the ACL Anthology is incorrect**, as shown in the following figure.
**The correct author name is as follows**, as it appears in the paper:

CCL 2023: Fixed the problem of spelling error of the author's name

---

data/yaml/sigs/siglex.yaml

> The SIGLEX Board agreed that SIGLEX should endorse the Global Wordnet Conferences, both the current ones and the past ones, retroactively. 
I am adding the list of past GWC events to the siglex page.

add GWC events in the siglex

---

bin/fixedcase/truelist
data/xml/W12.xml

Fixed casing in a single entry (`irvine-etal-2012-processing`) in W12.xml and updated the `truelist`.

Fixed casing in `irvine-etal-2012-processing` (W12)

---

.github/workflows/check-build.yml
.github/workflows/preview.yml
.github/workflows/publish.yml
Makefile

No breaking changes for us, but I added `--logLevel=info` to the Hugo invocation, and set the minimum required Hugo version to 0.114.x because that's when the `--logLevel` flag was introduced. I think it's fine to require a somewhat recent version even though the website technically builds with older versions.

Bump Hugo version from 0.108.0 to 0.118.2

---

data/xml/2023.acl.xml

The following publication has the wrong name of one of our collaborators:
**DOI:** 10.18653/v1/2023.acl-long.734 
**Paper title:** The Elephant in the Room: Analyzing the Presence of Big Tech in Natural Language Processing Research
The correct author's name is **Terry Ruas**.
The wrong one (in the paper's metadata) is **Terry Lima Ruas**.
This leads to the problem of showing the profile for [Terry Lima Ruas](https://aclanthology.org/people/t/terry-lima-ruas/) with just this **one** paper while the author has multiple papers in the ACL Anthology under [Terry Ruas](https://aclanthology.org/people/t/terry-ruas/).
The pull requests change the name in the publication from "Terry Lima Ruas" -> "Terry Ruas"
I am linking @truas to confirm.

Fix name mismatch by changing "Terry Lima Ruas" -> "Terry Ruas" in paper 2023.acl-long.734

---

bin/anthology/index.py
bin/anthology/papers.py

Attempts to fix #2863.
The way author/editor assignment is handled is currently terrible, and the way editors are added to papers without affecting author pages and paper counts feels like a terrible hack. In [the new library](https://github.com/mbollmann/acl-anthology-py/), there is already a clear distinction between information given explicitly in the XML vs. being implicitly inferred, so this should hopefully improve in the future.

Don't register co-editors for non-volume items

---

hugo/content/faq/feedback.md
hugo/content/faq/related-work.md
hugo/layouts/partials/header_navbar.html

I propose to add a prominent link to our Github repo to the website's navbar, in order to make it easier to discover.
We could make a button on the front page as well (analogous to the BibTeX download buttons), but I thought this would be nicer.

Add Github link to navbar

---

data/xml/2023.findings.xml

This is to fix the metadata associated with paper 2023.findings-emnlp.512, issue [https://github.com/acl-org/acl-anthology/issues/2920](https://github.com/acl-org/acl-anthology/issues/2920). 
The title was changed from: 
OLD: "Effects of Human Adversarial and Affable Samples on <fixed-case>BERT</fixed-case> Generalizability" 
NEW: "Effects of Human Adversarial and Affable Samples on <fixed-case>BERT</fixed-case> Generalization".
The abstract was also slightly changed to reflect the pdf.

 Fix issue  #2920: Paper Metadata: 2023.findings-emnlp.512 

---

bin/anthology/data.py
hugo/layouts/papers/single.html
hugo/layouts/volumes/single.html

Since 2017, DOI has changed their URL prefix from `http://dx.doi.org/` to `https://doi.org/`. This pull request updates the URLs in the ACL Anthology, making the links simpler, shorter, and more secure.
- https://www.doi.org/the-identifier/resources/factsheets/doi-resolution-documentation
- https://www.crossref.org/display-guidelines/

Use doi.org instead of dx.doi.org

---

data/xml/2023.emnlp.xml

This PR solves a naming error in EMNLP 2023 for my full name with a middle name (as opposed to just a first name). This way, the EMNLP 2023 articles will show in my [author profile](https://aclanthology.org/people/j/jan-philip-wahle/) instead of a [new author profile](https://aclanthology.org/people/j/jan-wahle/).

Update naming "Jan Wahle" -> "Jan Philip Wahle"

---

data/xml/2023.findings.xml

Anthology id: 2023.findings-emnlp.815
Adds the second name for my short paper accepted to findings of EMNLP to remain consistent with my remaining papers on ACL-Anthology.

fix: author name for 2023.findings-emnlp.815

---

data/xml/2023.emnlp.xml

Correction on surname. 
Explanation: My surname ("Chaves"), was mistaken by my middle name, given that I have 2 surnames ("Chaves Espinoza"). With this correction, the metadata will match the author's names in the paper's PDF. 
Here is my OpenReview profile for you to verify that I am one of the authors: https://openreview.net/profile?id=~Mariana_Chaves1

Correction in surname. Nothing to change on the paper's PDF

---

data/xml/2023.emnlp.xml

For Esteban the middle name "Garces" was missing, and for Matthias the last name was spelled wrong. We fixed this.

fixed names for publication 953

---

bin/anthology/texmath.py
tests/test_tex_math.py

When converting `<tex-math>` expressions to Unicode, the tail (= text after the closing tag) gets serialized twice.
Examples:
- https://aclanthology.org/2022.aacl-main.66/
- https://aclanthology.org/2022.findings-acl.24/
- https://aclanthology.org/2023.findings-emnlp.1054/ (closes #3004)
Note that the paper title heading on the page is correct, because that one uses the HTML conversion, whereas the duplication can be seen in the preformatted citation strings and also the HTML page title itself.
This bug must have existed ever since we introduced `<tex-math>` five years ago ...

Fix tex-math to unicode serialization

---

bin/create_bibtex.py

This restores human readability to the anthology.bib file while keeping the file size under 50 MB (#3016). It also adds a comment containing the bib file URL and the date it was generated.

Restore human readability and add header

---

data/xml/2023.finnlp.xml
data/xml/2023.ijcnlp.xml

FinNLP was accidentally overwritten with another workshop. This reverts that.
It appears that FinNLP might have had two meetings in 2023.

Reverted change to FinNLP

---

data/xml/2022.inlg.xml
data/xml/2022.semeval.xml
data/xml/2023.nodalida.xml

- 2023.nodalida.xml
- 2022.semeval.xml
- 2022.inlg.xml
_No response_
_No response_
Katya Artemova to Ekaterina Artemova 
I request the merging of two profiles in ACL Anthology, both associated with Ekaterina Artemova. While her papers in the PDF files are under Ekaterina Artemova, those submitted via OpenReview were published under the nickname Katya, leading to a separate profile.

Metadata correction for author name: Ekaterina Artemova

---

data/xml/2023.nlposs.xml

- Removed additional authors from https://aclanthology.org/2023.nlposs-1.26/ 
- Added abstracts to the invited talks.

Correcting and adding info to NLP-OSS workshop 2023 (`2023.nlposs.xml`)

---

data/xml/2023.eval4nlp.xml

There's a hallucinated author name in Eval4NLP 2023 xml. This PR corrects the author names

Update 2023.eval4nlp.xml, correct author names

---

data/xml/2023.emnlp.xml

Paper: 2023.emnlp-main.552 had the wrong title in the metadata, so it was showing a different title on the aclanthology page than the actual paper title. This is only a metadata issue, so no pdf needs to be uploaded.

fixed 2023.emnlp-main.552 title in metadata

---

data/xml/2022.acl.xml

There was a mix-up with the video links for papers 2022.acl-long.274 and 2022.acl-long.275 (see issue #3082). Initially, the video intended for paper 2022.acl-long.274 was incorrectly linked to 2022.acl-long.275, which was missing. I reached out to Underline, and they provided the correct video for paper 2022.acl-long.275. Both papers now have the appropriate videos linked. This issue stemmed from a mislabeling error at Underline.

[ACL 2022] Fixed incorrect video matching

---

python/CHANGELOG.md
python/acl_anthology/people/index.py
python/acl_anthology/people/person.py
python/tests/people/personindex_test.py
python/tests/toy_anthology/yaml/name_variants.yaml

Fixes a bug that could see canonical names defined in `name_variants.yaml` being overwritten by other name variants that scored higher according to our heuristics, and adds a test for it.

Don't overwrite canonical names that are explicitly defined in variants list

---

data/xml/2022.findings.xml

This is the actual paper: https://aclanthology.org/2022.findings-emnlp.391.pdf
You can see that the name "Kaushik Ram Sadagopan" in the pdf is not reflected correctly.

Author name correction in 2022.findings-emnlp.391

---

data/xml/2024.sigtyp.xml

Correcting the first name of author Ho Wang Matthew Sung. The author emailed us to report that "Ho Wang Matthew" is the correct first name. The XML had incorrectly truncated to "Ho" at export from OpenReview.

Update 2024.sigtyp.xml: Correcting author name as requested by author

---

bin/anthology/papers.py

Retracted papers whose title starts with a child (e.g., `<fixed-case>`) were not getting the "[RETRACTED]" prefix. This fixes that problem.

Fix retracted display for papers whose titles start with an lxml child

---

data/xml/2024.coling.xml
data/xml/2024.lrec.xml

The LREC-COLING 2024 workshops [signlang](https://aclanthology.org/volumes/2024.signlang-1/) and [BUCC](https://aclanthology.org/volumes/2024.bucc-1/) were ingested, but not listed in the volumes of the [lrec-2024](https://aclanthology.org/events/lrec-2024/) and [coling-2024](https://aclanthology.org/events/coling-2024/) events (see #3175). This corrects that.

Add 2 missing workshops to LREC-COLING 2024

---

.github/ISSUE_TEMPLATE/04-ingestion-request.yml

I have noticed that SIGs sponsoring/endorsing workshops are frequently forgotten and have to be added post hoc. This is a suggested way to fix this.
UPDATE: also address, which is sometimes inconsistent across volumes in the conference.

Ask about SIGs and address in ingestion form

---

data/xml/2023.emnlp.xml
data/xml/2024.lrec.xml

The goal of this edit is to collapse these two ACL Anthology pages:
https://aclanthology.org/people/c/christopher-jenkins/
and
https://aclanthology.org/people/c/chris-w-jenkins/
into this one:
https://aclanthology.org/people/c/chris-jenkins/
which reflects the contents of the pdfs in all cases
Thanks!

Correcting variations on first name to reflect pdf contents for author Chris Jenkins

---

data/yaml/name_variants.yaml

I have 2 acl profiles, as mentioed in this [issue#3353](https://github.com/acl-org/acl-anthology/issues/3353).
I don't mind publishing in both names as long as i can keep the acl profiles merged (with middle name and without):
https://aclanthology.org/people/a/amir-hossein-kargaran/ (default)
https://aclanthology.org/people/a/amir-kargaran/
affiliation: LMU Munich
I made the changes to reflect this.

Add variations of first name into name_variants.yaml

---

bin/ingest_mitpress.py
data/xml/2024.tacl.xml

* Changed volume from 11 to 12.
* There were additional papers available on the mitpress server, which I've included now.
* Modified `ingest_mitpress.py` such that it automatically stores `journal-volume` information. (I stored it manually, which led to the error.)

TACL 2024 journal volume fix

---

data/xml/2022.acl.xml
data/xml/2022.sigdial.xml
data/yaml/name_variants.yaml

(Similar to https://github.com/acl-org/acl-anthology/pull/3551)
I have two ACL profiles:
https://aclanthology.org/people/g/georgios-pantazopoulos/ (default)
https://aclanthology.org/people/g/george-pantazopoulos/ 
I would like to merge the two ACL profiles and being able to publish with both first name variants

feat: update name variants

---

data/xml/2024.bea.xml

The paper title metadata does not match the title in the PDF.
The authors corrected the title in the PDF and added a missing prefix for the shared task team name, but they did not update this information on Softconf. As a result, it was missing during the Softconf export when the proceedings were compiled.
For reference, see the PDF: https://aclanthology.org/2024.bea-1.55.pdf
For more details, see the issue: https://github.com/acl-org/acl-anthology/issues/3622

Update 2024.bea.xml for paper 2024.bea-1.55

---

data/xml/2024.bea.xml

The author list was truncated to the first 10 authors due to a bug in the aclpub2 tool.
For reference, see the PDF: https://aclanthology.org/2024.bea-1.51.pdf
For more details, see the issue: [#3621](https://github.com/acl-org/acl-anthology/issues/3621) 
The cause of this issue can be found in the aclpub2 GitHub repository, specifically in this issue: https://github.com/rycolab/aclpub2/issues/173 and this pull request: https://github.com/rycolab/aclpub2/pull/174
Although the issue was raised and the corrected version was forwarded to the NAACL 2024 publication chairs (past the proceedings deadline), it was not updated in the ACL Anthology.

Update 2024.bea.xml for paper 2024.bea-1.51

---

data/xml/2024.eacl.xml

My name is 'Jonathan K. Kummerfeld' in the pdf, but not in the metadata. See:
https://aclanthology.org/2024.eacl-long.11/
and
https://aclanthology.org/2024.eacl-long.11.pdf
This PR fixes the metadata.

Add middle initial to metadata that is in pdf

---

data/xml/2024.kallm.xml

Making metadata updates to match the PDF - 
1. For https://aclanthology.org/2024.kallm-1.1.pdf, update author order
2. For https://aclanthology.org/2024.kallm-1.13.pdf, add missing authors

Fix authors for two 2024.kallm papers

---

data/xml/2024.acl.xml

Corrections:
*Name and First name inverted: Yasser Hamidullah
*"van"  missing in Josef van Genabith
Issue: https://github.com/acl-org/acl-anthology/issues/3761

Update 2024.acl-short.40 in 2024.acl.xml

---

data/xml/2024.ml4al.xml

fixed minor misspellings to co-author names:
Evelien Graaf --> Evelien de Graaf
Tim Van De Cruys --> Tim Van de Cruys

Update co-author metadata 2024.ml4al.xml

---

data/xml/2024.loresmt.xml

I fixed the typo in the title. 
"Proceedings of the The Seventh ..." >> "Proceedings of the Seventh ...

fixed the typo in the LoResMT 2024 title (the The as the)

---

data/xml/2024.wassa.xml

Updating the xml entry for a paper submitted by my team for WASSA 2024 in Bangkok, Thailand. Modifying author's name listed in the xml entry to actual first and last name (entry instead includes email ID as both first and last name).

Update author name in 2024.wassa.xml for paper 38

---

data/xml/2023.nlposs.xml

This PR adds an author's name which seems to have been left out of the metadata of the _2023.nlposs-1.3_ paper. The author's name is present in the PDF but not in the metadata.

Addition of missing author

---

data/xml/2024.acl.xml

I am the author of the paper with Anthology ID: 2024.acl-long.748. Requesting updates to both the title and abstract of paper ID: 2024.acl-long.748 to ensure they match the PDF content. The current system title, “Prototypical Reward Network for Data-Efficient Model Alignment,” should be updated to “Prototypical Reward Network for Data-Efficient RLHF.” Additionally, the abstract needs alignment with the PDF to maintain accuracy and coherence.

Title and abstract correction for Anthology ID: 2024.acl-long.748

---

data/xml/2024.acl.xml

This pull request aims at fixing an encoding issue in the metadata of [this article](https://aclanthology.org/2024.acl-srw.20/).
The special character in one of the authors' name wasn't properly encoded.
The correct name of the author is as shown [in this other article](https://aclanthology.org/2023.semeval-1.195/).
It also fixes stuck words in the abstract.

BUG: fix encoding issue in data/xml/2024.acl.xml

---

data/xml/2024.iwslt.xml

Metadata corrections to one name on two papers in IWSLT 2024 ([1](https://aclanthology.org/2024.iwslt-1.1/) and [16](https://aclanthology.org/2024.iwslt-1.16/))

Metadata correction to name in IWSLT 2024

---

bin/create_bibtex.py

#3991 put the consolidated bib over 50 MB, breaking Overleaf compatibility. This brings it back down to ~46 MB, allowing us to kick file fragmentation down the road a bit.

Delete whitespace from consolidated bib

---

data/xml/2024.emnlp.xml

The title of our work in the ACL system doesn't match the title in our PDF, https://aclanthology.org/2024.emnlp-main.213.pdf
The title in the PDF is "VGBench: Evaluating Large Language Models on Vector Graphics Understanding and Generation", however the title in the ACL system is "VGBench: A Comprehensive Benchmark of Vector Graphics Understanding and Generation for Large Language Models". The title in the PDF is the correct one.

[2024.emnlp-main.213] Adjust the title of 2024.emnlp-main.213 to make it match to the PDF

---

data/xml/2024.wmt.xml

One co-author's name, María García-Abadillo Velasco, was incorrect. Furthermore, the title of the ACL Anthology entry did not match the pdf's title. It was updated to "Robustness of Fine-Tuned Models for Machine Translation with Varying Noise Levels: Insights for Asturian, Aragonese and Aranese" after incorporating the reviewers' feedback.
In the [pdf version](https://aclanthology.org/2024.wmt-1.89.pdf) of the paper everything is correct. The changes make the pdf consistent with the ACL Anthology website.

Correct title and author name for 2024.wmt-1.89

---

data/xml/2024.emnlp.xml

I am one of the authors of the paper "[More Insightful Feedback for Tutoring: Enhancing Generation Mechanisms and Automatic Evaluation](https://aclanthology.org/2024.emnlp-main.605.pdf)", 2024.emnlp-main.605.
The currently attached software is a preliminary version provided for review purposes only, we will provide an adapted version on github that meets company standards (linked in paper pdf). Therefore, we would like to request that the current software attachment is removed from the ACL anthology.

Remove software attachment for 2024.emnlp-main.605

---

data/yaml/venues/nodalida.yaml

This PR adds the [NoDaLiDa conference](https://aclanthology.org/venues/nodalida/) to the front page. Given the long history of the conference and that it is still active, I believe this is warranted.
(I am on the exec board of NEALT, which organizes NoDaLiDa, and this was brought up at a board meeting.)

Add NoDaLiDa to front page

---

data/xml/2023.nlposs.xml
data/xml/2024.mrl.xml

This PR changes the author information in the metadata of two papers to be consistent with the PDFs
Implements changes requested in #4068 and #4069

update metadata 2023.nlposs-1.2 and 2024.mrl-1.11

---

.github/ISSUE_TEMPLATE/99-bulk-metadata-correction.yml

Unfortunately YAML-based issues templates need to be under `master` to be tested. This will be used by #4146.

Add bulk metadata correction template

---

data/xml/W15.xml

Paper W15-4102 is the only one without a DOI in its volume, even though it exists and resolves:
- https://dx.doi.org/10.18653/v1/W15-4102

Add DOI for W15-4102

---

.github/ISSUE_TEMPLATE/99-bulk-metadata-correction.yml
bin/process_bulk_metadata.py
hugo/content/faq/corrections.md
hugo/content/info/corrections.md
hugo/content/posts/2024-12-27-new-metadata-workflow.md

Per #4229, the button was renamed in 055e8c3. This PR targets documentation pages mentioning the feature.

Shorten "Fix metadata" to "Fix data" in documentation and script

---

data/xml/2006.amta.xml

Fixes identical URL issues for the two AMTA 2006 panels. Closes #4155.

Fix wrong PDFs for AMTA 2006 panels

---

data/xml/2021.nejlt.xml
data/xml/2022.nejlt.xml
data/xml/2023.nejlt.xml
data/xml/2024.nejlt.xml

- Marks NEJLT volumes as 'journal'
- Adds 'journal-volume'
- Fixes publisher (NEALT is not a publisher; Linköping E-Press is)
- Fix DOI fields (2021–2023)
- Add DOIs (2024; oversight in my adaption of ACLPUB2 ...)

Fix NEJLT metadata

---

data/yaml/name_variants.yaml

name_variants.yaml: Added Gonçal Garcés with name variants
- Merging https://aclanthology.org/people/g/goncal-v-garces-diaz-munio/ and https://aclanthology.org/people/g/goncal-garces-diaz-munio/
- ORCID: https://orcid.org/0000-0002-2594-5858
- Academic website: https://www.upv.es/pls/oalu/sic_person.Info?p_alias=gogardia&P_IDIOMA=i

Added Gonçal Garcés with name variants

---

data/xml/2022.iwslt.xml

Correct author name (mine) to bring in line with PDF:
Added middle name as in PDF https://aclanthology.org/2022.iwslt-1.22.pdf
``<first>Gonçal</first>`` -> ``<first>Gonçal V.</first>``

Correct author name (mine) to bring in line with PDF

---

data/yaml/name_variants.yaml

I used to publish under Haoyue Shi before 2022 and then switched to Freda Shi. 
This PR includes my name variants.

Update Freda Shi name variants.

---

hugo/layouts/papers/single.html

I think these 2 strings will just be ignored when the bulk processing happens. But they are good for readability.

metadata correction issue JSON: store strings of old/new full author lists for easy comparison

---

bin/create_extra_bib.py

Seems like I introduced a Python indentation bug when creating the new script that generates the consolidated BibTeX. It causes journal articles to not appear in the uncompressed anthology.bib we generate.

Fix bug in consolidated BibTeX generation

---

data/xml/W11.xml

Removed redundant hyphen in `ahmed-etal-2011-challenges`.

Fixed bad hyphenation in `ahmed-etal-2011-challenges`.

---

data/xml/2023.acl.xml

`Bhasa-Abhijnaanam` was typeset as `Bhasa-abhijnaanam`.

Fixed casing in `madhani-etal-2023-bhasa`.

---

data/xml/2025.nlp4call.xml

My name was tokenized wrongly in the NLP4CALL workshop. I have corrected this and a similar issue with one of my coauthors.

Fixed authors' last names

---

bin/anthology/texmath.py
python/acl_anthology/text/texmath.py

This PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

Resolve warnings of logger library

---

.github/ISSUE_TEMPLATE/02-name-correction.yml

I feel like we are repeating this over and over and over again on new "author page" issues, so I propose to make this even more visible on the template. Exact formatting or wording up to discussion, of course.

Update name correction issue template

---

hugo/layouts/papers/single.html

Revert length limit on dialog submission

---

python/CHANGELOG.md
python/acl_anthology/utils/latex.py
python/tests/text/markuptext_test.py

Addresses #5320 by explicitly converting to/from LaTeX quotes (` `` '' ` and `` ` ' ``) if possible, instead of using `\textquotedblleft` etc.

Add more rules for LaTeX quote conversion

---

data/yaml/venues/naacl.yaml

Similar to #5572, NAACL was recently renamed to the "Nations of the Americas Chapter..." ([Source](https://naacl.org/posts/2024-10-24-Name-Change-Announcement)).
The latest volume names are fine; only the ACL Anthology header needs to be updated.
See: https://aclanthology.org/events/naacl-2025/
As in #5572, modifying the venue name in the YAML file will also change previous editions.
Thank you for your continuous efforts!

Rename NAACL to "Nations of the Americas Chapter..."

---

bin/create_hugo_data.py
hugo/content/people/_content.gotmpl
hugo/layouts/papers/single.html
hugo/layouts/partials/author_link.html
hugo/layouts/people/single.html
hugo/static/.htaccess

The current canonical author url is `/people/{letter}/{letter}{rest-of-slug}`. This removes the middle portion which is no longer necessary, resulting in a cleaner look. We give 301 redirects from the prior page.
@mbollmann do you have a minute to help me with the Hugo portion here? 
Closes #5627.

Update author page URIs

---

data/xml/schema.rnc

This causes integration tests on the Python library to fail otherwise due to a schema mismatch.

Undo schema change introduced by #5650

---

data/xml/schema.rnc

As per https://github.com/acl-org/acl-anthology/pull/5939#discussion_r2365876685
We haven't stored any ORCIDs as URLs yet, so no data changes are necessary.

Restrict schema to plain ORCID iDs

---

data/yaml/sigs/sigwrit.yaml

The landing page for [Special Interest Group on Writing systems and Written Language (SIGWrit)](https://aclanthology.org/sigs/sigwrit/) has two issues:
1.  There's a typo in the title.
2.  The original 2023 volume is missing.

[SIGWrit] Fixed a typo and added the original 2023 volume.

---

bin/fixedcase/truelist

- Four alternative terms for language families: Kartvelic, South/Northeast/Northwest Caucasian.
- More variants for individual language names + missing Tabasaran language.

[North Caucasus] Adding variants for names of languages and families.

---

bin/ingest.py
data/xml/2022.tal.xml
data/xml/2023.cl.xml
data/xml/2023.tal.xml
data/xml/2024.cl.xml
data/xml/2024.tal.xml

1. [x] In the Github sidebar, add the PR to the current milestone
1. [x] In the Github sidebar, add the PR to the "Anthology Work Items" project
1. [x] In the Github sidebar, under "Development", link to the corresponding ingestion issue (if applicable)
1. [x] …

Ingestion: TAL

---

hugo/content/faq/api.md
hugo/content/info/development.md

In #6088 I noticed [our API docs](https://preview.aclanthology.org/new-venue-faq-entry/info/development/) are way out of date. This is a minor update to improve that.

Minor update to the API docs
