acl-org/acl-anthology

- import/W06.xml
I removed a duplicate entry. This is present in [anthology.bib](http://aclanthology.info/anthology.bib), as well, which also contains some older errors that prevent BibTeX parsing.
> remove duplicate entry

- import/N18.xml
Incorporated the Vimeo links for each of the papers that had oral presentations that were recorded.
> Added conference presentation video links to NAACL 2018 papers

- import/P18.xml
Added attachments.
During rewriting file xml is converted in UTF-8 making symbols visible (rather than hex notation) which is in accordance with P17.xml
> added attachments

- import/D18.xml
Hi Matt, 
Thanks. We would like to correct the .bib file to reflect the order in the paper, and we just submitted an pull request with corrected authorship. Refer to the issue: https://github.com/acl-org/acl-anthology/issues/100. 
The link you mentioned is not corrected, which is https://github.com/acl-org/acl-anthology/blob/918dcc4dba25f07c09fe0807e3f6adbb8d589c6d/import/D18.xml#L5983.
Best,
Wei
> Authorship Correction in the .bib 

- app/views/static_pages/credits.html.erb
... and RAs from Min's group who helped with the dev of the Anthology.
> Added volunteers

- import/W18.xml
Already uploaded to aclweb.org
> Added v2 of W18-5120

- import/L12.xml
- import/S17.xml
- import/S18.xml
This PR replaces the name I no longer use with my current name, Robyn Speer.
> update author name to Robyn Speer on 3 papers

- import/N16.xml
Made changes to N16 for the filing of the revision and the presentation.  
PDF files of both revision and presentation posted to aclweb.org by me.
> Add revision and slides for N16-1085

- import/D10.xml
- import/N13.xml
- import/N16.xml
- import/O16.xml
- import/O90.xml
- import/O96.xml
- import/P07.xml
- import/P09.xml
- import/P13.xml
- import/R15.xml
- import/W05.xml
- import/W06.xml
- import/W07.xml
- import/W08.xml
- import/W09.xml
- import/W10.xml
- import/W11.xml
- import/W12.xml
- import/W13.xml
- import/W16.xml
- import/W17.xml
- import/W18.xml
- import/Y13.xml
Removes a number of affiliations in `<editor/>` lines (fixing #157).
> Editor corrections

- import/D14.xml
- import/E14.xml
- import/N15.xml
- import/P15.xml
- import/W14.xml
- import/W15.xml
- import/W16.xml
- import/W17.xml
- import/W18.xml
This should finally (I think) close #157.
> More editor corrections

- README.md
> adding info about installing the python requirements

- bin/anthology/people.py
- bin/create_hugo_yaml.py
- bin/find_name_variants.py
- hugo/layouts/people/single.html
Implements recent suggestions discussed in #86
> Update name variant handling

- data/yaml/sigs/siggen.yaml
> Updated siggen

- bin/LICENSE
- bin/add_revision.py
- bin/anthology/anthology.py
- bin/anthology/data.py
- bin/anthology/formatter.py
- bin/anthology/latexcodec.py
- bin/anthology/papers.py
- bin/anthology/people.py
- bin/anthology/sigs.py
- bin/anthology/texmath.py
- bin/anthology/utils.py
- bin/anthology/venues.py
- bin/anthology/volumes.py
- bin/bib2xml_wrapper
- bin/build_hugo
- bin/create_bibtex.py
- bin/create_hugo_pages.py
- bin/create_hugo_yaml.py
- bin/db_txt_to_yaml.sh
- bin/diff_xml.py
- bin/escapeXML.pl
- bin/merge_xml.py
- bin/normalize_anth.py
- bin/parsenames.pl
- bin/patch_fixedcase.py
- bin/split_sitemap.py
- bin/tex_unicode.py
Licensing this software under the Apache 2.0 license was agreed upon
by all contributors in GitHub issue #190.
> License the software under Apache 2.0

- data/yaml/name_variants.yaml
Hinrich Schütze
Arya D. McCarthy
> more name variants

- hugo/static/.htaccess
Adds our own `.htaccess` to the repository, including some updates.
@mjpost, can you triple-check this actually works and does what the commits say it does on the server before merging?
> Add .htaccess

- bin/anthology/volumes.py
A four-character PR to introduce an important `not`.
> Fix front matter logic (re #226)

- data/xml/D15.xml
- data/xml/D16.xml
- data/xml/D17.xml
- data/xml/N15.xml
- data/xml/N18.xml
- data/xml/P17.xml
- data/xml/P18.xml
- data/xml/Q14.xml
- data/xml/Q15.xml
- data/xml/Q16.xml
- data/xml/Q17.xml
- data/xml/Q18.xml
- data/xml/W18.xml
These are the ones that could be automatically linked.  I checked them
and removed two incorrect automatic matches.
The videos that could not automatically be linked as of now can be included later.
> Link to vimeo videos (see #167)

- README.md
Just minor additions that might be helpful to others.
> README: build time & how to serve locally

- bin/anthology/people.py
- data/xml/A83.xml
- data/xml/A97.xml
- data/xml/C67.xml
- data/xml/C80.xml
- data/xml/C88.xml
- data/xml/H90.xml
- data/xml/H91.xml
- data/xml/H92.xml
- data/xml/H93.xml
- data/xml/H94.xml
- data/xml/I05.xml
- data/xml/J04.xml
- data/xml/J05.xml
- data/xml/L00.xml
- data/xml/L14.xml
- data/xml/M98.xml
- data/xml/P18.xml
- data/xml/P91.xml
- data/xml/P95.xml
- data/xml/S12.xml
- data/xml/S13.xml
- data/xml/W03.xml
- data/xml/W16.xml
- data/xml/W98.xml
- data/xml/W99.xml
- data/xml/X96.xml
- data/yaml/name_variants.yaml
including single-name authors (closes #237)
> Minor name corrections

- data/xml/D17.xml
- data/xml/W16.xml
> Corrections for Raquel G. Alhama

- bin/anthology/papers.py
- bin/anthology/utils.py
- bin/anthology/volumes.py
- data/xml/P91.xml
- hugo/assets/css/main.scss
- hugo/layouts/events/single.html
- hugo/layouts/index.html
- hugo/layouts/search/results.html
- hugo/layouts/volumes/single.html
An assortment of bug fixes, and some documentation on the search results page.
The exact content/presentation of the search documentation is up for discussion, of course.
> Fixes & Search Documentation

- data/xml/W13.xml
Merging in @andreasvc's PR with a few additional changes.
> added IWPT13

- data/xml/C02.xml
- data/xml/C98.xml
- data/xml/L06.xml
- data/xml/L08.xml
- data/xml/L10.xml
- data/xml/L12.xml
- data/xml/L14.xml
- data/xml/N01.xml
- data/xml/P01.xml
- data/xml/P98.xml
- data/xml/R09.xml
- data/xml/W01.xml
- data/xml/W02.xml
- data/xml/W05.xml
- data/xml/W13.xml
- data/yaml/name_variants.yaml
Corrects some accents from changes in #231 and makes a few more corrections
> Eric Villemonte de la Clergerie

- data/xml/E93.xml
- data/xml/L00.xml
- data/xml/W04.xml
- data/yaml/name_variants.yaml
but these will eventually be converted to ids.
> WIP Last few first name completions

- data/xml/P18.xml
> fixed-case corrections from @nschneid (#279)

- data/xml/C00.xml
- data/xml/C98.xml
- data/xml/H92.xml
- data/yaml/name_variants.yaml
> minor corrections

- data/yaml/name_variants.yaml
> Rie Johnson

- bin/anthology/papers.py
- data/xml/J78.xml
> only export note to bib once

- data/xml/W03.xml
- data/yaml/sigs/sigparse.yaml
Addresses #286. Thanks to @kilian-gebhardt!
> Imported IWPT 2003

- data/yaml/name_variants.yaml
- hugo/layouts/people/single.html
> Published also as

- hugo/content/info/credits.md
> update my name & website

- data/xml/I05.xml
- data/xml/L18.xml
- data/yaml/name_variants.yaml
> Correcting the corrections to L18

- data/xml/L16.xml
> Correct L16-1745 (closes #341)

- data/xml/N19.xml
- data/xml/S19.xml
- data/xml/W19.xml
- data/yaml/name_variants.yaml
This will be merged first thing on June 2.
@davidweichiang, I have run `protect.py` on this, but what do you do for updating names?
> NAACL 2019 proceedings

- data/yaml/sigs/sighum.yaml
- data/yaml/sigs/siglex.yaml
- data/yaml/sigs/signll.yaml
- data/yaml/sigs/sigsem.yaml
- data/yaml/sigs/sigslpat.yaml
This currently has to be done manually, but it would be great to build this into the ingest XML so it could be automated. It's time-consuming.
> Added SIG affiliations to NAACL 2019

- .github/ISSUE_TEMPLATE/addition.md
- hugo/content/_index.md
Pointing people to the form instead.
> Change directions for adding attachments

- data/xml/Y18.xml
Replaced the original editor names with updated ones (as suggested by Matt in our e-mail correspondence).
> Updating editor names for Y18.xml

- bin/anthology/utils.py
- data/xml/W19.xml
Also added code to relativize URLs.
> Added WACL3

- data/xml/W19.xml
This pull request is to update a typo in my family name.
> Updated my name

- bin/anthology/utils.py
- data/xml/N19.xml
- data/xml/S19.xml
- data/xml/W19.xml
> DOIs for 2019 volumes

- data/xml/W19.xml
Updated editor names order to follow the PC order as on the WANLP
> Wanlp branch

- data/xml/J17.xml
Please double-check that this is now the correct DOI, we don't want to to this a third time :-)
> J17: Hopefully now really fix the DOI.

- data/xml/W19.xml
Papers were supposed to be non-archival, but were inadvertently submitted.
> Removed non-archival WiNLP'19 links (closes #508)

- data/xml/W19.xml
Missing author Chris Kirov from organizers page
> Update W19-4226 metadata

- data/xml/W19.xml
Fixing a copy-paste error in one of the titles.
> Fix paper title.

- data/xml/L16.xml
- data/xml/U06.xml
- data/yaml/name_variants.yaml
Names corrected: Pushpak Bhattacharyya, Oiwi Parker Jones, Eugenio Martinez Camara
> Corrections (thanks Gabe Orlansky at RPI)

- README.md
- README_detailed.md
Should be uncontroversial, makes the README.md shorter.
> Update readme for new make-based dependency installation

- data/xml/W19.xml
Some changes came through for NoDaLiDa'19. Since it hasn't been published yet, it's easier to process it this way. It's a small diff with a deadline of 30.09.
> NoDaLiDa'19 fix

- bin/anthology/anthology.py
- data/yaml/venues_joint_map.yaml
Also added NoDaLiDa workshops to venue page.
> check volume date against UTC time

- hugo/static/.htaccess
Sorry about the churn, but it seems that volume URLs are also broken. I put a fix in place and this makes it permanent.
> hotfix: volume URL

- Makefile
> Makefile: add split-sitemap, proper dependencies for venv

- Makefile
- bin/anthology/papers.py
- bin/anthology/utils.py
- bin/create_bibtex.py
- test/data/P19-1007.bib
- test/data/P19-1007.endf
- test/data/P19-1007.xml
I added a new test case to ensure this doesn't happen again. The first test should fail, then I'll push the code fix, which should pass.
> Restores bibtex URL (fixes #576)

- data/xml/N19.xml
> added video link

- data/xml/W19.xml
> W19-7808: XXX should be LiLa

- hugo/layouts/events/single.html
- hugo/static/.htaccess
these are live now
* redirect volume pages (closes #595)
* redirect non-www to www (closes #589, closes #569)
> redirect fixes

- hugo/static/.htaccess
This is currently tested and actually live.
> redirect nested file paths (closes #606)

- data/xml/D19.xml
Simple fix, see discussion at #619.
> Change title for D19-5527 (fixes #619)

- data/xml/D19.xml
This paper was retracted prior to publication but this was not
marked in START. As such we are removing it as if it had never
been published.
> removed paper

- data/yaml/name_variants.yaml
Hopefully then she will show up as one of the options on the Yang Liu page
> add Yang Liu as a variant for Yang (Janet) Liu

- bin/ingest.py
- data/xml/W19.xml
This isn't actually ready since there are LaTeX escapes in the names (not sure why this happened?)
> ingested derimo, updated script to check for PDFs

- data/xml/D19.xml
My name did not make it into the metadata - but it is in the pdf/source of the paper.
> Update D19.xml to fix author name for EMNLP workshop paper

- data/yaml/name_variants.yaml
update to name_variants.yaml to handle middle initial/name
> add john lalor name variants

- data/xml/D19.xml
You were too fast, here's a few more.
> manual fixes for #644

- data/xml/D19.xml
Corrections to spacing errors, and adding a new fixed-case.
> Corrections to D19-5634 title and abstract

- data/xml/D19.xml
Fix a typo in Author's name as explained in the issue #658
> Update `Ibrahim` name to `Ibraheem`

- bin/anthology/formatter.py
- bin/anthology/volumes.py
Hotfix for #655, if we're okay with using this solution for now.
> Hotfix for proceedings bib entries (fixes #655)

- .github/workflows/publish.yml
- Makefile
- README.md
Before merging:
@mjpost please add the secrets described in the README to the repository on github.
> Use GitHub actions to publish the anthology.

- data/xml/D18.xml
- data/xml/N18.xml
Hi! 
I recently changed my name; this PR reflects replacing instances of my old name ("Veronica") with my new name ("Skyler").
Thanks,
Skyler
> Name update

- data/xml/W19.xml
> Name correction: Dryjanski -> Dryjański

- data/xml/D19.xml
Request to update the author order for paper D19-5820, "Comprehensive Multi-Dataset Evaluation of Reading Comprehension".
Thanks!
>  update author order for D19-5820

- data/xml/D19.xml
https://github.com/acl-org/acl-anthology/issues/725
> Fix incorrect title for D19-5804 (https://github.com/acl-org/acl-anthology/issues/725)

- bin/anthology/formatter.py
- bin/author_case.py
- bin/ingest.py
- bin/upload_files.py
- data/xml/W19.xml
The other workshop cannot be located.
@davidweichiang, can you advise me on the new process for doing title correction and name checking? What scripts should I run? Now that I have some actual test data, once I have that, I'll incorporate them into the ingestion process and the documentation.
> added 3/4 INLG workshops

- hugo/content/faq/corrections.md
- hugo/content/info/corrections.md
Small change that eliminates some redundancy and adds a footnote about corrections.
> consolidated docs, added footnote

- data/xml/D19.xml
Inside the PDF the title is Unsupervised Question Answering for Fact-Checking. 
This PR corrects the name on the website by correcting the metadata.
> Corrected the title for D19-6609

- data/yaml/name_variants.yaml
My coauthor @adishalev changed her name.
> Adi Bitan as alias for Adi Shalev

- data/xml/R19.xml
- data/xml/W13.xml
- data/yaml/name_variants.yaml
Correct a paper's metadata and add the author to the name-variants file.
> Correct metadata (closes #749 closes #750)

- data/xml/A88.xml
- data/xml/E93.xml
- data/xml/P85.xml
- data/xml/P89.xml
- data/xml/W97.xml
- data/yaml/name_variants.yaml
Should have done this before merging #758
> Fix spelling

- data/xml/N19.xml
Added in the corrected NAACL 2019 video links to the anthology XML.
Fixes #763
> NAACL 2019: Added corrected video links to anthology.

- data/xml/K18.xml
- data/xml/L18.xml
- data/xml/N18.xml
- data/xml/P18.xml
- data/xml/P19.xml
- data/xml/W19.xml
Affects: K18-3001, L18-1293, N18-2085, N18-2087, P18-1245, P19-1161, P19-1491, W19-4226.
> Replace deadname with Sabrina J. Mielke

- .github/ISSUE_TEMPLATE/file-a-correction.md
- hugo/content/info/corrections.md
I am simplifying the instructions for corrections.
> Update issue templates

- data/xml/W16.xml
[The metadata](https://www.aclweb.org/anthology/W16-2517/) lists only Naomi Saphra as an author, but [the PDF](https://www.aclweb.org/anthology/W16-2517.pdf) additionally lists Adam Lopez, so I added him to the metadata.
> Fix author list of W16-2517

- data/xml/W17.xml
Author order changed to reflect the PDF.
> Change author order in W17-1706 (resolves #753)

- hugo/layouts/index.html
This PR will make COLING 1984 appear on the front page and resolves #748.
> Add 1984 (resolves #748)

- data/xml/L14.xml
adds one missing abstract in L14
> abstract for L14-1412

- data/xml/W15.xml
> added URL to PDF (#598)

- data/xml/1991.iwpt.xml
- data/xml/1993.iwpt.xml
- data/xml/1995.iwpt.xml
- data/xml/1997.iwpt.xml
- data/xml/2000.iwpt.xml
- data/xml/W13.xml
Sorry for all the changes, but for consistency with all the other IWPTs, I prepended "Proceedings of the" to the new workshops.
https://www.aclweb.org/anthology/venues/iwpt/
> added 'proceedings of the'

- data/xml/2007.sigdial.xml
- data/yaml/sigs/sigdial.yaml
> added missing space

- data/yaml/venues.yaml
Not sure to what extent this effects other files, let me know if more changes are needed and I will do a more detailed pass. Thanks!
> Correct RepL4NLP acronym

- hugo/content/info/contrib.md
Due to transition to new ID schema
> Fix broken URL

- bin/create_bibtex.py
- hugo/layouts/index.html
Creates `/anthology/anthology+abstracts.bib.gz` (per https://github.com/acl-org/acl-anthology/issues/243#issuecomment-638268998).
> add full anthology with abstracts (#243)

- data/xml/E14.xml
Adjust author legal name on an EACL 2014 paper
> Update author name

- hugo/layouts/index.html
Button line break and table width.
> Fix minor front-page layout issues

- data/xml/R19.xml
- data/xml/W18.xml
- data/yaml/name_variants.yaml
Nicolov requested changing his name on several already-published papers as well; this PR doesn't do that (yet).
> Merge pages for Nicola I. Nicolov (#865)

- data/yaml/name_variants.yaml
> Name variants for Nikola Nikolov

- data/xml/2020.acl.xml
- data/xml/2020.framenet.xml
- data/xml/2020.lrec.xml
- data/yaml/name_variants.yaml
> Tiago T. Torrent

- data/xml/D17.xml
- data/xml/D19.xml
- data/xml/L14.xml
- data/xml/N18.xml
- data/xml/P19.xml
- data/xml/W17.xml
- data/xml/W18.xml
Affected: D17, D19, L14, N18, P19, W17, W18
Thanks!
> Replace deadname with Jasmijn

- data/xml/2015.jeptalnrecital.xml
Fix the issues (and a couple of more regarding the use of `È` instead of `è`) reported in https://github.com/acl-org/acl-anthology/pull/849#issuecomment-656185766
> 2015.jeptalnrecital: fix accent and escaping issues

- data/xml/2020.sigdial.xml
Method: scraped public videos on youtube w/ firefox, then emacs
macros.  Some papers have no public video, these are not linked.
> add sigdial 2020 videos

- data/xml/D18.xml
- data/xml/D19.xml
Updated first author name to Nikita Srivatsan for D19-1225 and D18-1496. PDFs have already been updated similarly.
> Updated first author name to Nikita Srivatsan for D19-1225 and D18-1496

- data/xml/2020.sigdial.xml
Correcting my name to match other publications in the anthology
> Update 2020.sigdial.xml - Name correction

- bin/likely_name_split.py
- data/yaml/name_variants.yaml
#908 
new routine best_split can be called from ingestion script.
> new script to parse names into first/last

- data/xml/2020.nlp4convai.xml
- hugo/content/info/corrections.md
Also updated the documentation with the name revision policy.
> corrected metadata for 2020.nlp4convai-1.13

- bin/create_hugo_pages.py
- bin/ingest.py
- data/xml/2019.jeptalnrecital.xml
- data/xml/2020.jeptalnrecital.xml
The data shouldn't change, but the volume order might, so if you approve, please don't merge.
> Ingest jep/taln/recital 2019 and 2020

- bin/ingest_tsv.py
- data/xml/2020.amta.xml
- data/yaml/name_variants.yaml
Ingesting AMTA 2020's research volume.
We have a bit of a backlog on PRs, but it would be nice if this could go through right away (maybe @danielgildea or @davidweichiang has a minute to approve?)
> Ingest AMTA 2020 research volume

- data/xml/2020.tlt.xml
> International Workshop on Treebanks and Linguistic Theories

- data/xml/2016.jeptalnrecital.xml
- data/xml/2020.amta.xml
- data/xml/F12.xml
- data/xml/L10.xml
- data/xml/L14.xml
- data/xml/L16.xml
- data/xml/W14.xml
- data/xml/W18.xml
- data/yaml/name_variants.yaml
- data/yaml/venues.yaml
- hugo/content/info/contrib.md
I'm accumulating miscellaneous fixes here. Most of these should be pretty non-controversial I think.
> Misc fixes

- data/xml/2020.emnlp.xml
fix issue #1065: update title for 2020.emnlp-main.488
> Correction to 2020.emnlp-main.488

- data/xml/2020.sustainlp.xml
Correct name misspelling:
https://github.com/acl-org/acl-anthology/issues/1075#issuecomment-728594832
Thanks!
> Update 2020.sustainlp.xml - correct name misspelling

- bin/fix_titles.py
- bin/fixedcase/truelist
- data/xml/2020.alw.xml
- data/xml/2020.blackboxnlp.xml
- data/xml/2020.clinicalnlp.xml
- data/xml/2020.codi.xml
- data/xml/2020.conll.xml
- data/xml/2020.deelio.xml
- data/xml/2020.nlpbt.xml
- data/xml/2020.splu.xml
- data/xml/2020.sustainlp.xml
- data/xml/2020.wnut.xml
The wrong titles were submitted from EMNLP. This contains more fixes.
> EMNLP workshop title fixes

- bin/ingest_tsv.py
- bin/likely_name_split.py
- data/xml/2020.amta.xml
Ingesting AMTA workshop. One more will follow.
> AMTA corrections

- data/xml/2020.coling.xml
- data/yaml/joint.yaml
- data/yaml/venues.yaml
> COLING fixes

- data/xml/2020.udw.xml
This one could use a quick approval, please.
> Revision to 2020.udw-1.22 (closes #1152)

- data/xml/2020.semeval.xml
per https://semeval.github.io/semeval2020-awards.html
> SemEval 2020 awards (and missing spaces in an abstract)

- bin/anthology/utils.py
- data/xml/2020.ccl.xml
- data/xml/2020.coling.xml
- data/xml/2020.emnlp.xml
- data/xml/2020.fever.xml
- data/xml/2020.inlg.xml
- data/xml/2020.latechclfl.xml
- data/xml/2020.repl4nlp.xml
- data/xml/2020.sdp.xml
- data/xml/2020.starsem.xml
- data/xml/2020.wat.xml
- data/xml/D18.xml
- data/xml/D19.xml
- data/xml/P19.xml
- data/xml/W18.xml
- data/xml/W19.xml
- data/yaml/name_variants.yaml
Processing corrections. A work in progress.
> Corrections

- data/yaml/venues.yaml
> COLING name: not ICCL

- data/xml/W11.xml
- data/yaml/name_variants.yaml
Hello,
This merges the pages of "Michael White" and "Mike White".
> add name variants

- data/xml/2020.webnlg.xml
- data/yaml/joint.yaml
- data/yaml/sigs/siggen.yaml
Hello,
This adds the WebNLG workshop to SIGGEN.
It also fixes the volume id as mentioned in #1190 (Hope I got it right.)
> add webnlg to siggen

- Makefile
replaces #1227.
Just adds an if/else to use empty rules instead of the real ones if NOBIB=true
Also includes the checks from #1227.
> Conditional bibtex generation

- bin/ingest_mitpress.py
- data/xml/2020.cl.xml
- data/xml/2021.tacl.xml
> Ingesting TACL and CL

- data/xml/N13.xml
- data/xml/P15.xml
- data/xml/Q13.xml
- data/xml/Q15.xml
Removed techtalks.tv links per #1241.
Removals are in the PR, of course, but for reference, this affects:
* N13
* P15
* Q13
* Q15
> Removed techtalks links

- data/xml/2021.eacl.xml
- data/yaml/name_variants.yaml
Changes so that my name matches the rest of the anthologies entries
> fixed my first name in EACL 2021

- bin/ingest.py
- data/xml/2017.jeptalnrecital.xml
- data/xml/2021.semdeep.xml
- data/yaml/name_variants.yaml
- data/yaml/venues.yaml
Semdeep was mistakenly given the wrong venue code.
> Corrected venue code

- data/xml/2019.icon.xml
> ingested ICON2019

- data/xml/2021.alvr.xml
ALVR (part of NAACL 2021) mistakenly submitted non-archival papers. This removes them.
> Reingested ALVR without non-archival papers

- data/xml/2021.eacl.xml
Re #240
Source: https://2021.eacl.org/best-paper/
> Add EACL 2021 best paper awards

- .github/workflows/preview.yml
As per https://github.com/acl-org/acl-anthology/pull/1095#issuecomment-860644763
> Remove NOBIB=true flag for preview branches

- .github/ISSUE_TEMPLATE/file-a-correction.md
This is getting out of hand, let's give people an even more explicit pointer regarding author changes.
> gh issue template: Add instructions for author changes

- data/yaml/name_variants.yaml
this puts 2021.nodalida-main.46 on the right author page
> add name variant for myself

- data/xml/2014.amta.xml
See https://aclanthology.org/www.mt-archive.info/10/AMTA-2014-TOC.htm for original.
> Ingest AMTA 2014.

- Makefile
> Makefile: quote possibly empty variable

- data/xml/1993.mtsummit.xml
See https://aclanthology.org/www.mt-archive.info/90/MTS-1993-TOC.htm for original.
* No abstracts since papers do not have these
* Everything as a single volume to prevent overvolumization
> Ingested MT Summit 1993.

- data/xml/1995.mtsummit.xml
See https://aclanthology.org/www.mt-archive.info/90/MTS-1995-TOC.htm for the original.
> Ingested MT Summit 1995.

- data/xml/2006.jeptalnrecital.xml
- data/xml/2009.jeptalnrecital.xml
- data/xml/2018.gwc.xml
- data/xml/2020.blackboxnlp.xml
- data/xml/2020.inlg.xml
- data/xml/2020.wnut.xml
- data/xml/2021.bionlp.xml
- data/xml/2021.cmcl.xml
- data/xml/2021.naacl.xml
- data/xml/2021.nlp4if.xml
> Corrections for June 2021

- data/xml/1999.mtsummit.xml
See https://aclanthology.org/www.mt-archive.info/90/MTS-1999-TOC.htm for original.
> Ingested MT Summit 1999.

- data/xml/1991.mtsummit.xml
See https://aclanthology.org/www.mt-archive.info/90/MTS-1991-TOC.htm for original.
> Ingested MT Summit 1991.

- data/xml/1997.mtsummit.xml
See https://aclanthology.org/www.mt-archive.info/90/MTS-1997-TOC.htm for original.
> Ingested MT Summit 1997.

- bin/anthology/bibtex.py
- bin/ingest.py
- data/xml/2018.ijclclp.xml
- data/xml/2019.ijclclp.xml
- data/xml/2020.ijclclp.xml
> Ingest IJCLCLP 18 19 20

- data/xml/2015.mtsummit.xml
See https://aclanthology.org/www.mt-archive.info/15/MTS-2015-TOC.htm for original.
> Ingested MT Summit 2015.

- data/xml/2009.mtsummit.xml
See https://aclanthology.org/www.mt-archive.info/05/MTS-2009-TOC.htm for original.
> Ingested MT Summit 2009.

- data/xml/1980.tc.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/70/Aslib-1980-TOC.htm for original.
> Ingested TC 1980.

- data/xml/1997.tc.xml
See https://aclanthology.org/www.mt-archive.info/90/Aslib-1997-TOC.htm for original.
> ingested tc 1997

- data/xml/1984.tc.xml
- data/xml/schema.rnc
See https://aclanthology.org/www.mt-archive.info/70/Aslib-1984-TOC.htm for original.
> ingested tc 1984

- data/xml/1995.tc.xml
See https://aclanthology.org/www.mt-archive.info/90/Aslib-1995-TOC.htm for original.
> ingested tc 1995

- data/xml/1981.tc.xml
- data/xml/schema.rnc
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/70/Aslib-1981-TOC.htm for original.
> Ingested TC 1981.

- data/xml/1988.tc.xml
- data/xml/1998.tc.xml
- data/xml/2013.tc.xml
- data/xml/schema.rnc
See https://aclanthology.org/www.mt-archive.info/10/Aslib-2013-TOC.htm for original.
> Ingest tc 2013

- data/xml/1998.tc.xml
- data/xml/2011.tc.xml
See https://aclanthology.org/www.mt-archive.info/10/Aslib-2011-TOC.htm for original.
> Ingest tc 2011

- data/xml/1998.tc.xml
- data/xml/2012.tc.xml
See https://aclanthology.org/www.mt-archive.info/10/Aslib-2012-TOC.htm for original.
> Ingest tc 2012

- data/xml/1998.tc.xml
- data/xml/2010.tc.xml
See https://aclanthology.org/www.mt-archive.info/10/Aslib-2010-TOC.htm for original.
> Ingest tc 2010

- data/xml/1998.tc.xml
- data/xml/2009.tc.xml
See https://aclanthology.org/www.mt-archive.info/05/Aslib-2009-TOC.htm for original.
> Ingest tc 2009

- data/xml/1998.tc.xml
- data/xml/2008.tc.xml
See https://aclanthology.org/www.mt-archive.info/05/Aslib-2008-TOC.htm for original.
> Ingest tc 2008

- data/xml/1997.tmi.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/90/TMI-1997-TOC.htm for original.
> Ingested TMI 1997.

- data/xml/1993.tmi.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/90/TMI-1993-TOC.htm for original.
> Ingested TMI 1993.

- data/xml/1985.tmi.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/70/TMI-1985-TOC.htm for original.
Unfortunately there are no PDFs available.
> Ingested TMI 1985.

- data/xml/1988.tmi.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/70/TMI-1988-TOC.htm for original.
I processed as a single volume because otherwise things get messy. What do you think?
> Ingested TMI 1988.

- data/xml/1992.tmi.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/90/TMI-1992-TOC.htm for original.
> Ingested TMI 1992.

- data/xml/1999.tmi.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/90/TMI-1999-TOC.htm for original.
> Ingested TMI 1999.

- data/xml/2005.iwslt.xml
See https://aclanthology.org/www.mt-archive.info/05/IWSLT-2005-TOC.htm for original.
> Ingested IWSLT 2005.

- data/xml/1985.tc.xml
- data/xml/schema.rnc
See https://aclanthology.org/www.mt-archive.info/70/Aslib-1985-TOC.htm for original.
* I have combined the biographical notes and the list of participants into a single pdf (this is the backmatter).
> ingested tc 1985

- data/xml/1994.tc.xml
See https://aclanthology.org/www.mt-archive.info/90/Aslib-1994-TOC.htm for original.
> ingested tc 1994

- data/xml/1993.tc.xml
See https://aclanthology.org/www.mt-archive.info/90/Aslib-1993-TOC.htm for original.
> ingested tc 1993

- data/xml/1992.tc.xml
- data/xml/schema.rnc
See https://aclanthology.org/www.mt-archive.info/90/Aslib-1992-TOC.htm for original.
> ingested tc 1992

- data/xml/1990.tc.xml
- data/xml/schema.rnc
See https://aclanthology.org/www.mt-archive.info/90/Aslib-1990-TOC.htm for original.
* I have combined the biographical notes and the list of participants into a single pdf (this is the backmatter).
> ingested tc 1990

- data/xml/1998.tc.xml
- data/xml/2007.tc.xml
See https://aclanthology.org/www.mt-archive.info/05/Aslib-2007-TOC.htm for original.
> Ingest tc 2007

- data/xml/1998.tc.xml
See https://aclanthology.org/www.mt-archive.info/90/Aslib-1998-TOC.htm for original.
> ingested tc 1998

- data/xml/1998.tc.xml
- data/xml/1999.tc.xml
See https://aclanthology.org/www.mt-archive.info/90/Aslib-1999-TOC.htm for original.
> Ingest tc 1999

- data/xml/1998.tc.xml
- data/xml/2000.tc.xml
See https://aclanthology.org/www.mt-archive.info/00/Aslib-2000-TOC.htm for original.
> Ingest tc 2000

- data/xml/1998.tc.xml
- data/xml/2001.tc.xml
See https://aclanthology.org/www.mt-archive.info/00/Aslib-2001-TOC.htm for original.
> Ingest tc 2001

- data/xml/1998.tc.xml
- data/xml/2002.tc.xml
- data/xml/2005.mtsummit.xml
See https://aclanthology.org/www.mt-archive.info/00/Aslib-2002-TOC.htm for original.
> Ingest tc 2002

- data/xml/1998.tc.xml
- data/xml/2003.tc.xml
See https://aclanthology.org/www.mt-archive.info/00/Aslib-2003-TOC.htm for original.
> Ingest tc 2003

- data/xml/1998.tc.xml
- data/xml/2004.tc.xml
See https://aclanthology.org/www.mt-archive.info/00/Aslib-2004-TOC.htm for original.
> Ingest tc 2004

- data/xml/1998.tc.xml
- data/xml/2006.tc.xml
See https://aclanthology.org/www.mt-archive.info/05/Aslib-2006-TOC.htm for original.
> Ingest tc 2006

- data/xml/2021.mtsummit.xml
> Update Kelly Marchisio name in 2021.mtsummit.xml

- data/xml/1991.tc.xml
See https://aclanthology.org/www.mt-archive.info/90/Aslib-1991-TOC.htm for original.
> ingested tc 1991

- data/xml/1989.tc.xml
- data/xml/schema.rnc
See https://aclanthology.org/www.mt-archive.info/70/Aslib-1989-TOC.htm for original.
* I have combined the biographical notes and the list of participants into a single pdf (this is the backmatter).
> Ingest tc 1989

- data/xml/1987.tc.xml
- data/xml/schema.rnc
See https://aclanthology.org/www.mt-archive.info/70/Aslib-1987-TOC.htm for original.
* I have combined the biographical notes and the list of participants into a single pdf (this is the backmatter).
> ingested tc 1987

- data/xml/2002.tmi.xml
- data/xml/2004.tmi.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/00/TMI-2004-TOC.htm for original.
> Ingest tmi 2004

- data/xml/2021.findings.xml
Steven Feng --> Steven Y. Feng for 2021.findings-acl.84
> Changes to 2021.findings-acl.84

- data/xml/2016.tc.xml
See https://aclanthology.org/www.mt-archive.info/15/Asling-2016-TOC.htm for original.
* Even though there is not publisher mentioned on the website, a web search reveals that AsLing is the publisher.
* The PDF link for `Translation quality evaluation of MWE from French into English using an SMT system` is not working, so I have omitted the PDF.
> ingested tc 2016

- data/xml/2014.tc.xml
See https://aclanthology.org/www.mt-archive.info/10/Asling-2014-TOC.htm for original.
> ingested tc 2014

- data/xml/2006.iwslt.xml
See https://aclanthology.org/www.mt-archive.info/05/IWSLT-2006-TOC.htm for original.
> Ingested IWSLT 2006.

- data/xml/2015.iwslt.xml
See https://aclanthology.org/www.mt-archive.info/15/IWSLT-2015-TOC.htm for original.
> ingested iwslt 2015

- data/xml/2021.cnl.xml
- data/yaml/venues.yaml
> cnl 2021 ingestion

- data/xml/2006.bcs.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/05/BCS-2006-TOC.htm for original.
> ingested bcs 2006

- data/xml/1994.bcs.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/90/BCS-1994-TOC.htm for original.
> ingested bcs 1994

- data/xml/1984.bcs.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/70/BCS-1984-TOC.htm for original.
> Ingested BCS 1984

- data/xml/2012.iwslt.xml
See https://aclanthology.org/www.mt-archive.info/10/IWSLT-2012-TOC.htm for original.
> ingested iwslt 2012

- data/xml/2014.iwslt.xml
See https://aclanthology.org/www.mt-archive.info/10/IWSLT-2014-TOC.htm for original.
> ingested iwslt 2014

- data/xml/2000.bcs.xml
- data/yaml/venues.yaml
See https://aclanthology.org/www.mt-archive.info/00/BCS-2000-TOC.htm for original.
> ingested bcs 2000

- data/xml/2013.mtsummit.xml
See https://aclanthology.org/www.mt-archive.info/10/MTS-2013-TOC.htm for original.
> Ingested MT Summit 2013.

- data/xml/1994.bcs.xml
- data/xml/1997.eamt.xml
- data/xml/2003.mtsummit.xml
- data/xml/2005.mtsummit.xml
- data/xml/2007.sigdial.xml
- data/xml/2008.eamt.xml
- data/xml/2011.mtsummit.xml
- data/xml/2012.iwslt.xml
- data/xml/W03.xml
fixes build error on master branch
plus some other name fixes
> fix duplicate bibkey

- data/xml/2015.tc.xml
See https://aclanthology.org/www.mt-archive.info/15/Asling-2015-TOC.htm for original.
> ingested tc 2015

- data/xml/2021.inlg.xml
Steven Feng --> Steven Y. Feng for 2021.inlg.xml
> Changes to 2021.inlg.xml

- hugo/content/info/credits.md
@mbollmann Maybe you want to update yours as well, did not want to do that without your input.
> Update my affiliation

- .github/ISSUE_TEMPLATE/file-a-correction.md
- .gitignore
- Makefile
- README.md
- README_detailed.md
- bin/add_bulk_attachments.py
- bin/auto_authors.py
- bin/repair_url.py
- bin/upload_files.py
- google-cse/annotations.xml
- google-cse/cse.xml
- hugo/content/faq/related-work.md
- hugo/content/info/contrib.md
- hugo/content/info/ids.md
- hugo/layouts/sitemap.xml
- test/data/P19-1007.bib
- test/data/P19-1007.endf
- test/data/P19-1007.xml
There were a number of missed domain conversions from #1328. I think this might be affecting our search results (#1658) because some of them were in the custom search engine. This may also have been affecting the sitemapindex, but I'm not sure.
> Finished domain conversion

- bin/ingest_mitpress.py
- data/xml/2021.cl.xml
- data/xml/2021.tacl.xml
Required a bit of reworking of the script. CL is coming next.
> Ingest CL and TACL through 2021

- data/xml/2021.acl.xml
The title in the metadata does not match the one in the pdf.
**Description of changes**
I changed the title in the metadata to match the one in the pdf.
> Correction to Anthology ID 2021.acl-long.191

- data/yaml/sigs/siggen.yaml
> Remove duplicate INLG 2021

- data/xml/2021.eacl.xml
@xinru1414 can you approve and merge this asap?
> Revision to 2021.eacl-main.117 (closes #1798)

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/file-a-correction.md
- hugo/content/info/corrections.md
This is a draft policy update under discussion in #1873.
> Proposed update to authorship changes policy

- data/xml/2022.iwslt.xml
Adds the missing abstract to IWSLT22 paper #10
> add missing abstract

- data/xml/2022.csrr.xml
> Fix metadata for paper 2022.csrr-1.1

- data/xml/2020.aacl.xml
I removed my middle names from the metadata. This reflects how Victor Milewski is written in the PDF and is in line with the ACL2022 metadata.
> Update metadata for 2020.aacl-main.50

- data/xml/2022.iwslt.xml
Author correction to match pdf for 2022.iwslt-1.18
> Metadata correction for 2022.iwslt-1.18

- data/xml/2022.findings.xml
The attachment is removed. Our source code will not be shared at this moment.
> Correct metadata for paper 2022.findings-acl.161

- data/xml/2022.findings.xml
Correcting the Author name for the paper ID: 2022.findings-acl.245. Name has been changed from "Serra Tekiroglu" to "Serra Sinem Tekiroğlu".
> Update 2022.findings.xml ID: 2022.findings-acl.245

- data/xml/2022.acl.xml
Fix Issue #1931: 
https://github.com/acl-org/acl-anthology/issues/1931
> Metadata fix for 2022.acl-tutorials.3

- data/xml/2022.eamt.xml
Correction of the author's name
My name is Mikołaj Pokrywka not Miko Pokrywka :) (In the paper the name is correct)
Anthology ID: 2022.eamt-1.48
URL: https://aclanthology.org/2022.eamt-1.48
> Correction first name, AnthologyID: 2022.eamt-1.48

- data/xml/2022.findings.xml
> Correction to title of 2022.findings-acl.151

- data/xml/2022.naacl.xml
- data/yaml/joint.yaml
- data/yaml/sigs/sigedu.yaml
- data/yaml/sigs/siglex.yaml
- data/yaml/sigs/sigmorphon.yaml
- data/yaml/sigs/sigsem.yaml
- data/yaml/sigs/sigtyp.yaml
Accumulating corrections here that we should merge tonight.
@xinru1414 if you (or someone else) can pre-approve, it would be helpful. These will not be controversial.
> NAACL'22 additions

- data/xml/2022.acl.xml
- data/xml/2022.naacl.xml
fixing my name in 2022 papers.
> fixing my name in 2022 papers

- data/xml/2022.insights.xml
Added middle name initial to match naming in the paper's PDF.
> Corrected author name

- data/xml/2022.nlppower.xml
Update 2022.nlppower.xml
The author's name should be first name: "Byoung Chan" and last name: "Lee".
> Correction to Anthology ID 2022.nlppower-1.3

- .github/workflows/paperswithcode.yml
- .github/workflows/preview.yml
- .github/workflows/publish.yml
- Makefile
- bin/anthology/latexcodec.py
fix some harmless warnings just to be tidy
> fix build warnings

- data/xml/2022.germeval.xml
> Fix spelling of author name

- data/xml/2022.amta.xml
Made corrections to the author sections , the co-authors of the paper Anthology ID 2022.amta-research.21 were missing so i have added them.
> Added missing coauthors to 2022.amta-research.21

- data/xml/2022.lrec.xml
Fixes https://github.com/acl-org/acl-anthology/issues/2161
> Correction to Anthology ID 2022.lrec-1.326

- data/xml/2021.blackboxnlp.xml
- data/xml/2021.codi.xml
- data/xml/2021.conll.xml
- data/xml/2021.crac.xml
- data/xml/2021.econlp.xml
- data/xml/2021.emnlp.xml
- data/xml/2021.eval4nlp.xml
- data/xml/2021.fever.xml
- data/xml/2021.findings.xml
- data/xml/2021.insights.xml
- data/xml/2021.latechclfl.xml
- data/xml/2021.mrl.xml
- data/xml/2021.mrqa.xml
- data/xml/2021.newsum.xml
- data/xml/2021.nlp4convai.xml
- data/xml/2021.sustainlp.xml
- data/xml/2021.wmt.xml
- data/xml/2021.wnut.xml
* added missing EMNLP videos.
* added EMNLP workshops (these were mostly missing).
> added missing EMNLP 2021 videos

- data/xml/2022.lrec.xml
LREC 2022: Fix casing for paper 692.
> LREC 2022: Fix title casing for paper 692

- data/xml/2022.ccl.xml
Changed the author firstname and surname order. Please refer to this Github Issue: 
https://github.com/acl-org/acl-anthology/issues/2193
> Paper ID 2022.ccl-1.73 author name correction

- .github/workflows/preview.yml
Many thanks to @mchick! https://github.com/mshick/add-pr-comment/issues/28
> Update preview message instead of making a new one

- data/xml/2022.acl.xml
- data/xml/2022.bigscience.xml
- data/xml/2022.bionlp.xml
- data/xml/2022.cmcl.xml
- data/xml/2022.computel.xml
- data/xml/2022.constraint.xml
- data/xml/2022.csrr.xml
- data/xml/2022.deelio.xml
- data/xml/2022.dialdoc.xml
- data/xml/2022.dravidianlangtech.xml
- data/xml/2022.ecnlp.xml
- data/xml/2022.fever.xml
- data/xml/2022.findings.xml
- data/xml/2022.humeval.xml
- data/xml/2022.in2writing.xml
- data/xml/2022.insights.xml
- data/xml/2022.lchange.xml
- data/xml/2022.lnls.xml
- data/xml/2022.ltedi.xml
- data/xml/2022.mml.xml
- data/xml/2022.nlp4convai.xml
- data/xml/2022.nlppower.xml
- data/xml/2022.repl4nlp.xml
- data/xml/2022.slpat.xml
- data/xml/2022.spanlp.xml
- data/xml/2022.spnlp.xml
- data/xml/2022.wassa.xml
- data/xml/2022.wit.xml
* added main conference videos
* added workshop videos
> ACL 2022 videos

- hugo/layouts/partials/header_navbar.html
> Add preview warning

- data/xml/2022.gem.xml
Fixed wrong paper title in anthology ID 2022.gem-1.21 (issue #2350).
> Correction to Anthology ID 2022.gem-1.21

- data/xml/2022.sustainlp.xml
**Please be sure to add the Anthology ID in the Issue title**
Please review [our correction policy](https://aclanthology.org/info/corrections/), then fill out the information below.
*For the second author the middle name is missing in meta data, I added the middle name which is similar with the name in the PDF*
> This revision corrects a missed name in Author list for the second author
> Correction to Anthology ID 2022.sustainlp-1.11

- data/xml/2018.tal.xml
- 1 switch last name / first name (Morin Emmanuel => Emmanuel Morin)
- 1 spelling correction (procesing => processing)
> correction of 2 minor errors in 2018.tal.xml

- data/xml/2011.tal.xml
- Villemont de La Clergerie => Villemonte de La Clergerie
- Walthe => Walther
> 2 corrections of author names in 2011.tal.xml

- data/xml/2022.amta.xml
Soumya Chennabasavraj to Soumya Chennabasavaraj
[updated 2022.amta-research.7.pdf](https://github.com/acl-org/acl-anthology/files/10956901/updated.2022.amta-research.7.pdf)
> Updated author spelling of 2022.amta-research.7

- data/xml/2023.eacl.xml
Adds all 13 paper awards for EACL 2023.
> EACL paper awards

- Makefile
I don't have the faintest idea why this [suddenly started failing](https://github.com/acl-org/acl-anthology/actions/runs/4891671614/jobs/8732559779), but tests on my machine suggest that this might fix it.
> Fix pre-commit run in make check

- data/xml/2023.eacl.xml
- data/xml/2023.latechclfl.xml
- data/xml/2023.loresmt.xml
> Spelling fix 2023.eacl-main.28

- data/xml/2023.resourceful.xml
minor changes to the list of editors in data/xml/2023.resourceful.xml
> update the list of editors of the workshop proceedings

- data/xml/2023.resourceful.xml
Updating the list of editors again
> Update the list of editors of the proceedings [2]

- bin/fixedcase/truelist
- data/xml/J10.xml
- data/xml/W09.xml
> Fixed casing for the Indus script and the authors in the related discussion.

- data/xml/2023.findings.xml
Paper id: 2023.findings-eacl.50 required author name correction. The last author was missing their middle name. This PR fixes that issue.
> Update to 2023.findings-eacl.50

- data/xml/2023.iwslt.xml
* Paper 1: Added missing first author in metadata (Milind Agarwal)
* Paper 40: Corrected typo in first name of first author (Seungjun)
> Made two metadata corrections to names in IWSLT 2023.

- data/xml/L14.xml
- data/xml/W09.xml
Two papers titles I noticed that didn't match the PDF.
> Fix paper titles to match PDF

- data/xml/2023.bionlp.xml
Incorrect author first name: `Franois` should be changed to `François`
> Fix #2642 (Paper Metadata: remy-etal-2023-automatic)

- data/xml/2022.naacl.xml
Match the authors' names with the PDF #2691
> Fix #2691 (Paper Metadata: 2022.naacl-main.143)

- data/xml/2023.semeval.xml
Removed repeated determiner from the title ([Proceedings of _the The_ 17th International Workshop on Semantic Evaluation (SemEval-2023)](https://aclanthology.org/2023.semeval-1.0.pdf)).
> Fixed a spelling mistake 

- data/xml/2022.tal.xml
> Quick fix: Added new volume attribute

- bin/add_dois.py
- data/xml/2022.emnlp.xml
- data/xml/2022.tsar.xml
> TSAR 2022 fixes (#2363)

- .github/workflows/check-build.yml
- .github/workflows/preview.yml
- .github/workflows/publish.yml
Update workflows that involve building the website to hopefully use the new larger runner, re #2800.
> Update workflow runners

- data/xml/W04.xml
- data/yaml/name_variants.yaml
Mike published two papers as Mike.
> Update name_variants.yaml for Mike Collins

- data/xml/2023.sigdial.xml
I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.
2023.sigdial-1.18
Paper Title
[INCORRECT] Question Generation to Elicit Users' Food Preferences Considering the Semantic Content
**[CORRECT] Question Generation to Elicit Users' Food Preferences by Considering the Semantic Content**
> Paper Metadata: 2023.sigdial-1.18

- data/xml/2023.wat.xml
> Paper Metadata: 2023.wat-1.4

- data/xml/2023.emnlp.xml
Match the authors' names with the PDFs for #2908 (2023.emnlp-main.185) and #2907 (2023.emnlp-main.785)
> Fix authors' names

- data/xml/2023.conll.xml
Match the authors' name with the PDF
> Paper Metadata: 2023.conll-1.6

- data/xml/2023.findings.xml
I want to file corrections to make the metadata match the PDF file hosted on the ACL Anthology.
Anthology ID: 2023.findings-emnlp.841 
Correction to Author Name(s): Thinh Pham, Chi Tran, Dat Quoc Nguyen
> Correct author name(s) - paper metadata: 2023.findings-emnlp.841

- data/xml/2023.emnlp.xml
Meta-data correction. First name is "Jia Peng" instead of "Jia" as per PDF (https://aclanthology.org/2023.emnlp-main.534.pdf).
Linked to #2944
> Update author name for 2023.emnlp-main.534

- data/xml/2023.emnlp.xml
Update title to match the PDF.
https://aclanthology.org/2023.emnlp-main.447.pdf
Fixes #2954
> Update title for 2023.emnlp-main.447

- data/xml/2020.louhi.xml
- data/xml/W19.xml
2020.louhi-1.6, W19-3219
No response
No response
Correction to the name of the first author:
First name: Selene
Last name: Baez Santamaria
Same author as in https://aclanthology.org/people/s/selene-baez-santamaria/
These should appear under the same author page, but appear as having been authored by two different people at the moment.
> Paper Metadata: 2020.louhi-1.6, W19-3219

- bin/create_bibtex.py
This gets `anthology.bib` to 41 MB. To make it smaller, I
* Removed newlines and extra spaces from each entry
* Used two global string substitutions, and another per-volume one for the book title
> Shrink anthology.bib (closes #3016)

- data/xml/2023.emnlp.xml
> Add umlaut

- data/xml/2023.emnlp.xml
This removes revisions from papers that were meant to be replaced, not revised.
> Remove revisions

- data/xml/2023.arabicnlp.xml
Update in Metadata in 2023.arabicnlp:
- Correct Author First Name in two publications in the same conference.
> Update Metadata in 2023.arabicnlp

- .pre-commit-config.yaml
- Makefile
- bin/add_attachment.py
- bin/add_bulk_attachments.py
- bin/anthology/utils.py
- bin/create_bibtex.py
- bin/normalize_joint_yaml.py
- bin/requirements.txt
- pyproject.toml
- python/poetry.lock
- python/pyproject.toml
~Should not affect existing code.~ Affects a few scripts outside of the new library.
(Doing this PR also to check our Github setup when merging into the `python-dev` branch.)
> Update Python dependencies

- data/xml/2021.sigmorphon.xml
- data/xml/W10.xml
- data/xml/W19.xml
- data/yaml/name_variants.yaml
Add entry for `Fred Mailhot` and variants
> Add Fred Mailhot to name_variants.yaml

- .github/workflows/code-quality.yml
- .github/workflows/preview.yml
- bin/create_hugo_yaml.py
- python/CHANGELOG.md
- python/acl_anthology/collections/paper.py
- python/acl_anthology/collections/volume.py
- python/acl_anthology/data/acl.csl
- python/acl_anthology/people/name.py
- python/acl_anthology/utils/__init__.py
- python/acl_anthology/utils/citation.py
- python/docs/api/utils.md
- python/poetry.lock
- python/pyproject.toml
- python/tests/collections/paper_test.py
- python/tests/collections/volume_test.py
- python/tests/people/name_test.py
This PR adds citeproc functionality into the new library.
> Add Citeproc functionality

- .github/workflows/code-quality.yml
- bin/create_hugo_yaml.py
- python/CHANGELOG.md
- python/acl_anthology/people/index.py
- python/acl_anthology/people/person.py
- python/tests/people/personindex_test.py
(Side effect: Testing if Codecov will comment on this.)
> Adds function to find co-authors with paper counts

- data/xml/2022.semeval.xml
Spelling Change
Name spelling change corresponding to Issue #3233 .
> Metadata fix to 2022.semeval-1.21

- data/xml/2023.acl.xml
- data/xml/2023.blackboxnlp.xml
- data/xml/2024.eacl.xml
- data/xml/D13.xml
- data/xml/J98.xml
- data/xml/P13.xml
- data/xml/P98.xml
Adds EACL2024 awards. Closes #3152
> Adds ACL'23 and EACL'24 Awards

- data/yaml/sigs/sigwrit.yaml
This adds a YAML file for SIGWrit and links to our first meeting at LREC-COLING 2024.
> Adds SIGWrit to the YAML files.

- data/xml/2022.coling.xml
This is part of #3287, but I think we should process retractions separately since it's important they go through in a timely manner.
> Add retraction

- test.py
The implementation passed local tests but failed for this repository. 
To check if the following two actions are triggered: 
- print-info Use the printed messages to debug
- link-to-checklist
1. [ ] In the Github sidebar, add workshop to work items and the current milestone
1. [ ] In the Github sidebar, make sure to link to a corresponding PR under "Development"
1. [ ] Make sure the branch is merged with the latest `master` branch
1. [ ] Ensure that there are editors listed in the `<meta>` block
1. [ ] If it's a workshop, add a `<venue>ws</venue>` tag
1. [ ] Look at the venue listing for prior years, and ensure that the new volume titles are consistent. You can do this by clicking on the venue name from a paper page, which will take you to the …
> Ingestion: Test ingestion checklist

- .github/ISSUE_TEMPLATE/02-name-correction.yml
YAML folded style to replace newlines with spaces
> 02-name-correction.yml: formatting

- data/xml/2024.nlpcss.xml
Fixing my name in NLP+CSS 2024 proceedings
> fixing my name in NLPCSS 2024

- data/xml/2023.insights.xml
- data/xml/2024.clinicalnlp.xml
The first name is changed from "Faizan" to "Faizan E" as mentioned in the author's name inside the paper.
> [2023 Insights] Metadata change

- data/xml/2024.semeval.xml
Fixing Alvin's name in semeval pub
> Name fix for 2024.semeval-1.263

- data/xml/2024.naacl.xml
Issue: #3642
Paper Metadata: {2024.naacl-long.202}
> Add authors to 2024.naacl-long.202

- data/xml/1994.vlc.xml
See https://preview.aclanthology.org/ingest_vlc_1994/volumes/1994.vlc-1/
> Ingestion: Second Workshop on Very Large Corpora (1994)

- data/xml/2023.icon.xml
Command used:
```bash
perl -pi -e "s/<first>(.*?)<(.*)><last>(.*?)</<first>\3<\2><last>\1</" data/xml/2023.icon.xml
```
I have not checked for errors.
> Correct reversed names (closes #3677)

- data/xml/2021.winlp.xml
- data/xml/2022.sigul.xml
Adding my sir name at 2023.emnlp.xml
> Name correction

- bin/anthology/latexcodec.py
- data/xml/2024.jeptalnrecital.xml
- data/xml/2024.tacl.xml
also, fix python warning from string escapes
> fix build error from duplicate bibkeys

- data/xml/2024.loresmt.xml
Fix #3736.
The name of the first author should be "King Yiu Suen" rather than "King Suen": https://aclanthology.org/people/k/king-yiu-suen/
> Paper Metadata: 2024.loresmt-1.8

- data/xml/2024.scil.xml
1. [ ] In the Github sidebar, add the PR to work items and the current milestone …
> Ingestion SCIL 2024

- data/yaml/name_variants.yaml
I have changed my surname (Schüz -> Junker) and created a new entry in name_variants.yaml for this.
Thanks!
> Update name_variants.yaml for myself

- data/xml/2024.alvr.xml
Fixes one of the authors's name in 2024.alvr-1.17 as raised in #3800.
> Correct author's name of 2024.alvr-1.17

- data/xml/2024.iwslt.xml
Correction to Author Name(s)
Xi Xu and Siqi Ouyang and Brian Yan and Patrick Fernandes and William Chen and Lei Li and Graham Neubig and Shinji Watanabe
Issue:
https://github.com/acl-org/acl-anthology/issues/3778
> Correction for Paper Metadata: {2024.iwslt-1.20} #3778

- .github/ISSUE_TEMPLATE/01-metadata-correction.yml
modeled after the blurb on the author correction template
> metadata correction issue template: suggest a PR instead

- data/xml/2023.repl4nlp.xml
Adding middle initials to two names, as submitted to the conference
> Correcting author names

- data/xml/2021.acl.xml
- data/xml/2021.emnlp.xml
- data/xml/2022.emnlp.xml
- data/xml/2022.lrec.xml
- data/xml/2023.acl.xml
I have profiles under two different variations of my name. This commit merges them to maintain consistency and avoid confusion.
> Merge profiles under different name variations into a single profile

- data/xml/2020.sltu.xml
Corrected names to be in line with the PDF.
> Paper metadata 2020.sltu.xml

- data/xml/2024.repl4nlp.xml
Waiting for more information from the RepL4NLP organizers.
> Provisional removal of extended abstracts

- data/xml/2024.wassa.xml
A redo of the previous pull request, but this time I tested and compiled it successfully on my local machine.
This is just a fix of the metadata (my name) of our paper at the WASSA workshop.
> fixed metadata for my name in 2024 wassa paper (version fixed)

- data/xml/2024.cl.xml
> Ingestion: CL Volume 50 Issue 3

- data/xml/2024.ctt.xml
- data/xml/2024.eamt.xml
- data/xml/2024.gitt.xml
- data/xml/2024.kemt.xml
- data/yaml/venues/ctt.yaml
- data/yaml/venues/gitt.yaml
- data/yaml/venues/kemt.yaml
> Ingestion: EAMT 2024

- data/xml/2022.naacl.xml
the video has mistakes that need correction
> mistakes in video

- data/xml/2024.amta.xml
> Ingestion: AMTA 2024

- data/xml/2023.genbench.xml
https://aclanthology.org/2023.genbench-1.11.pdf
> complete the abstract in the paper (2023.genbench-1.11)

- data/xml/2024.textgraphs.xml
https://aclanthology.org/2024.textgraphs-1.3.pdf
> 2024.textgraphs-1.3: title, abstract spaces

- data/xml/2024.sigdial.xml
- data/xml/2024.yrrsds.xml
> Ingestion: yrrsds 2024

- data/xml/2024.nlp4call.xml
- data/yaml/sigs/sigedu.yaml
> Ingestion: NLP4CALL

- data/xml/2024.acl.xml
- data/xml/2024.hcinlp.xml
- data/xml/2024.safety4convai.xml
Closes #3977 
I noticed a name mismatch affecting some co-authors too, so I fixed those as well. (Checked against the PDF in all cases.)
> Fix names to match PDF (Alba Curry, Amanda Cercas Curry, Flor Miriam Plaza-del-Arco)

- data/xml/2024.nlp4call.xml
Fixed the name in our paper from NLP4CALL this year.
This should fix issue #3973
> Fixed author name for 2024.nlp4call-1.11

- data/xml/2024.icnlsp.xml
> Ingestion: ICNLSP 24

- data/xml/2023.jlcl.xml
- data/yaml/venues/jlcl.yaml
> Ingestion: JLCL

- data/xml/2024.wmt.xml
As Described in the Issue, I am raising a PR to correct the username along with first author correction.
Issue: #4009
> corrected username for wmt metadata

- data/xml/2024.wmt.xml
Correcting author names (2024.wmt-1.76):
The correct name for the 4th author is "Bharathi Raja Chakravarthi"; "Raja" is missing.
The correct name for the 6th author is "John Philip McCrae"; "Philip" is missing.
> Correcting author names (2024.wmt-1.76)

- data/xml/2024.tacl.xml
> Ingestion: TACL 2024 (updated with new papers)

- data/xml/2024.emnlp.xml
- data/xml/2024.fever.xml
my last and first names are mistakenly swapped.
> swap first and last names {2024.emnlp-main.922}

- data/yaml/venues/jlcl.yaml
- hugo/layouts/index.html
Not sure why we didn't do this before! Every year this trips me up.
Also add JLCL to the main page.
> Add variable columns to the front page

- data/xml/2024.inlg.xml
- data/yaml/sigs/siggen.yaml
> Ingestion: INLG additional

- data/xml/2020.sltu.xml
- data/xml/2021.eacl.xml
- data/xml/L16.xml
- data/yaml/name_variants.yaml
I'm fixing my name in the anthology. Please let me know if there are any other files to modify — but it seems that this successfully merges the two author profiles that have been created for me (i.e., for "[Santos, Eddie](https://aclanthology.org/people/e/eddie-santos/)" and "[Antonio Santos, Eddie](https://aclanthology.org/people/e/eddie-antonio-santos/)").
> Fix name for Eddie Antonio Santos

- data/xml/2024.swisstext.xml
- data/yaml/sigs/sigsem.yaml
> Ingestion: SwissText 2024

- data/yaml/sigs/sigarab.yaml
- data/yaml/venues/arabicnlp.yaml
Resolves #4127
This adds SIGARAB, linking the meetings indicated in #4127, and adds ArabicNLP to the frontpage.
> Establish SIGARAB

- .github/ISSUE_TEMPLATE/99-bulk-metadata-correction.yml
- .github/hidden-templates/bulk-metadata-correction.yml
We don't want this one to show up in the list of issues.
> Test hidden bulk template

- python/CHANGELOG.md
- python/pyproject.toml
This is the first new release in over a year, which should now be feature-complete w.r.t. building the entire website.
> Bump to version v0.5.0

- .github/ISSUE_TEMPLATE/99-bulk-metadata-correction.yml
I want to make sure this is working separately before announcing in #4223
> Fix issue template

- bin/process_bulk_metadata.py
- data/xml/2023.finnlp.xml
- data/xml/2023.mtsummit.xml
- data/xml/2024.acl.xml
- data/xml/2024.cl4health.xml
- data/xml/2024.dravidianlangtech.xml
- data/xml/2024.iwclul.xml
- data/xml/2024.sighan.xml
- data/xml/2024.teachingnlp.xml
- data/xml/C82.xml
- data/xml/W18.xml
This semi-automatic PR also includes some fixes to the bulk corrections script:
- Changes are made locally, then pushed at the end
- Now correctly handles multiple changes to the same file
The following issues are affected:
- closes #4281
- closes #4278
- closes #4276
- closes #4269
- closes #4268
- closes #4267
- closes #4263
- closes #4261
- closes #4258
- closes #4255
- closes #4252
- closes #4246
- closes #4245
- closes #4234
- closes #4221
- closes #4182
- closes #4177
- closes #4173
- closes #4168
- closes #4164
> Bulk metadata corrections 2025-01-01

- .github/workflows/publish.yml
Fixes build failure because I forgot yet another place to update the Hugo version ...
> Update Hugo version in publish workflow

- hugo/layouts/papers/single.html
Encourages correction-submitters to check all authors
> checkbox for metadata edits: be more specific

- .github/workflows/annotate-metadata-issue.yml
> Get anthology_id consistently

- data/xml/2020.acl.xml
- data/xml/2020.coling.xml
- data/xml/2021.ranlp.xml
- data/xml/2021.sigdial.xml
- data/xml/2021.socialnlp.xml
- data/xml/2022.findings.xml
- data/xml/2023.acl.xml
- data/xml/2024.lrec.xml
- data/xml/S12.xml
- data/xml/S15.xml
- data/xml/S16.xml
- data/xml/S17.xml
- data/xml/W13.xml
- data/xml/W16.xml
- data/xml/W18.xml
- data/xml/W19.xml
https://aclanthology.org/2020.coling-main.559.pdf is hard to edit, left unchanged
https://aclanthology.org/L12-1470/ do not know where the PDF is http://www.lrec-conf.org/proceedings/lrec2012/pdf/796_Paper.pdf
> Vanja M. Karan name update.

- data/xml/2024.nejlt.xml
1. [ ] In the Github sidebar, under "Development", make sure to link to the corresponding issue …
> Ingestion: NEJLT Volume 10

- bin/create_hugo_data.py
Sorting logic was wrong, this will fix that and close #4383.
> Fix co-author and venue sorting, fixes #4383

- data/xml/2024.luhme.xml
Fix 2 minor remaining parsing errors
> Luhme changes for pr 4381

- data/xml/2024.nlp4musa.xml
> Ingestion: nlp4musa 2024

- data/yaml/name_variants.yaml
Merge the pages:
- https://aclanthology.org/people/h/hakaze-cho/
- https://aclanthology.org/people/y/yufeng-zhao/
**Github issue**: https://github.com/acl-org/acl-anthology/issues/4444
> Merge Author Names

- data/xml/2024.tlt.xml
> Ingestion: TLT 2024

- bin/fixedcase/truelist
- data/xml/2025.indonlp.xml
> truelist: Sri Lankan

- hugo/static/cgi-bin/extract_citation.cgi
> Fix regex and boolean

- bin/ingest_aclpub2.py
- data/xml/2023.conll.xml
- data/xml/2024.conll.xml
- data/yaml/venues/babylm.yaml
> Ingestion: BabyLM

- data/xml/2024.acl.xml
- data/xml/2024.lrec.xml
- data/xml/2024.nlp4musa.xml
- data/xml/2025.coling.xml
> Corrections: 2025 Feb

- data/yaml/name_variants.yaml
merge the author pages of "Anirudh Sundar" and "Anirudh S. Sundar"
> Added anirudh name variant

- bin/fixedcase/truelist
- data/xml/2009.mtsummit.xml
- data/xml/2024.emnlp.xml
- data/xml/2024.naacl.xml
- data/xml/C14.xml
- data/xml/L10.xml
- data/xml/P13.xml
- data/xml/W16.xml
Fixing a bunch of existing entries as well as updating the `truelist`.
> Adding fixed-case handling for `Babel`.

- bin/fixedcase/truelist
- data/xml/2024.cl.xml
- Adding `Bronze Age` to `truelist`.
- Fixing casing in `braovic-etal-2024-systematic`.
> Adding `Bronze Age` to `truelist`, fixing casing of one entry

- bin/ingest.py
- data/xml/2024.umrpw.xml
- data/yaml/sigs/siglex.yaml
- data/yaml/venues/umrpw.yaml
1. [ ] In the Github sidebar, add the PR to work items and the current milestone
1. [ ] In the Github sidebar, under "Development", make sure to link to the corresponding issue
1. [ ] Make sure the branch is merged with the latest `master` branch
1. [ ] Ensure that there are editors listed in the `<meta>` block
1. [ ] Look at the venue listing for prior years, and ensure that the new volume titles are consistent. You can do this by clicking on the venue name from a paper page, which will take you to the vendor listing.
1. [ ] Navigate to the event page preview (e.g., …
> Ingestion: UMRPW

- data/xml/2023.clicit.xml
> Ingestion: CliC-it 2023

- data/xml/2025.naacl.xml
> Updated author name for Chenghao Zhu

- data/yaml/name_variants.yaml
> Add name variant for Chao-Han Huck Yang

- data/yaml/name_variants.yaml
> Add name variants for Muhammad N. ElNokrashy

- data/yaml/name_variants.yaml
Update name_variants.yaml: kranti-chalamalasetti
> Update name_variants.yaml: kranti-chalamalasetti

- .github/workflows/link-to-checklist.yml
- data/xml/2025.iwsds.xml
- data/yaml/venues/iwsds.yaml
> Ingest IWSDS

- data/yaml/name_variants.yaml
> Added name variant for Nishat Raihan

- data/xml/2024.paclic.xml
> Ingestion PACLIC 2024

- bin/process_bulk_metadata.py
- data/xml/2024.acl.xml
- data/xml/2024.emnlp.xml
- data/xml/2024.lrec.xml
- data/xml/2024.paclic.xml
- data/xml/2025.coling.xml
- closes #5440
- closes #5436
- closes #5430
- closes #5426
- closes #5425
- closes #5424
- closes #5423
- closes #5419
> Bulk metadata corrections 2025-07-11

- data/xml/2022.dlg4nlp.xml
- data/xml/2022.emnlp.xml
- data/xml/2022.findings.xml
- data/xml/2023.eacl.xml
- data/xml/2023.emnlp.xml
- data/xml/2023.tacl.xml
- data/xml/2024.acl.xml
- data/xml/2024.emnlp.xml
- data/xml/2024.knowledgenlp.xml
- data/xml/2025.findings.xml
- data/xml/2025.naacl.xml
- data/xml/P19.xml
- data/yaml/name_variants.yaml
> Added Author Page  for Zhihan Zhang

- data/xml/2025.dmr.xml
> Ingestion: dmr

- data/xml/2021.gem.xml
- data/xml/2022.fieldmatters.xml
- data/xml/2022.gem.xml
- data/xml/2024.fieldmatters.xml
- data/xml/2025.fieldmatters.xml
- data/xml/2025.gem.xml
- data/xml/2025.llmsec.xml
- data/xml/2025.semeval.xml
- data/yaml/sigs/sigsec.yaml
- data/yaml/venues/llmsec.yaml
1. [x] In the Github sidebar, add the PR to the current milestone
1. [x] In the Github sidebar, add the PR to the "Anthology Work Items" project
1. [x] In the Github sidebar, under "Development", link to the corresponding ingestion issue (if applicable)
1. [x] …
> Ingestion: missing ACL workshops

- bin/add_author_id.py
- data/xml/2020.acl.xml
- data/xml/2020.coling.xml
- data/xml/2020.emnlp.xml
- data/xml/2020.findings.xml
- data/xml/2021.acl.xml
- data/xml/2021.emnlp.xml
- data/xml/2021.findings.xml
- data/xml/2022.coling.xml
- data/xml/2022.emnlp.xml
- data/xml/2022.findings.xml
- data/xml/2022.nlp4convai.xml
- data/xml/2023.acl.xml
- data/xml/2023.dstc.xml
- data/xml/2023.eacl.xml
- data/xml/2024.acl.xml
- data/xml/2024.emnlp.xml
- data/xml/2024.lrec.xml
- data/xml/2025.cl.xml
- data/xml/2025.coling.xml
- data/xml/2025.findings.xml
- data/xml/2025.naacl.xml
- data/xml/D10.xml
- data/xml/D19.xml
- data/xml/P06.xml
- data/xml/S16.xml
- data/xml/W09.xml
- data/yaml/name_variants.yaml
> Author page: Chen Zhang

- data/yaml/name_variants.yaml
> Merge author pages for Sarah Masad Preum

- data/yaml/name_variants.yaml
> Typo: Masad -> Masud in name_variants.yaml canonical name

- data/yaml/name_variants.yaml
> Added name variant for Sergio José Rodríguez Méndez

- data/yaml/name_variants.yaml
> Added name variant for Sai Kartheek Reddy Kasu

- data/yaml/name_variants.yaml
> Add name variant for Chau Minh Pham

- data/yaml/name_variants.yaml
> Added name variant for Pascale Feldkamp

- data/xml/2024.acl.xml
- data/xml/2025.coling.xml
- data/xml/2025.findings.xml
- data/xml/2025.naacl.xml
- data/yaml/name_variants.yaml
> Add author page for Chaoqun Liu

- data/xml/2022.emnlp.xml
- data/xml/2022.findings.xml
- data/xml/2023.acl.xml
- data/xml/2023.sustainlp.xml
- data/xml/2024.acl.xml
- data/xml/2025.semeval.xml
- data/xml/2025.trustnlp.xml
- data/yaml/name_variants.yaml
> Add author page for Xin Xu

- data/xml/2021.eacl.xml
- data/xml/2025.naacl.xml
- data/yaml/name_variants.yaml
> Add author page for Mohan Zhang

- data/xml/2020.acl.xml
- data/xml/2020.findings.xml
- data/xml/2022.emnlp.xml
- data/xml/2024.lrec.xml
- data/xml/2025.insights.xml
- data/xml/A00.xml
- data/xml/C10.xml
- data/xml/L00.xml
- data/xml/L08.xml
- data/xml/N03.xml
- data/xml/N04.xml
- data/yaml/name_variants.yaml
> Author page david evans mit

- bin/ingest_aclpub2.py
- data/xml/2025.clasp.xml
1. [x] In the Github sidebar, add the PR to the current milestone
1. [x] In the Github sidebar, add the PR to the "Anthology Work Items" project
1. [x] In the Github sidebar, under "Development", link to the corresponding ingestion issue (if applicable)
1. [x] …
> Ingest CLASP 2025

- data/xml/2021.findings.xml
- data/xml/2023.acl.xml
- data/xml/2023.emnlp.xml
- data/xml/2024.acl.xml
- data/xml/2025.knowllm.xml
- data/xml/2025.naacl.xml
- data/yaml/name_variants.yaml
> Added author page for Yue Deng

- data/yaml/name_variants.yaml
> Added name variant for Richard He Bai

- data/xml/2020.acl.xml
- data/xml/2024.emnlp.xml
- data/yaml/name_variants.yaml
> Added author page for Tianyang Zhang

- data/xml/2021.tacl.xml
- data/xml/2025.semeval.xml
> Bulk metadata corrections 2025-09-09

- data/xml/2025.naacl.xml
- data/xml/L18.xml
- data/yaml/name_variants.yaml
> Added author page for Le Chen

- bin/fixedcase/truelist
> truelist: Tajiki

- data/yaml/name_variants.yaml
> Added author page for Yudong Wang

- data/xml/2025.findings.xml
- data/yaml/name_variants.yaml
> Added author page for Heyuan Huang

- data/yaml/name_variants.yaml
> Added name variant for Eddie L. Ungless

- data/xml/2023.semeval.xml
- data/xml/2024.law.xml
- data/xml/2024.lrec.xml
- data/xml/2025.sdp.xml
- data/xml/2025.trl.xml
- data/yaml/name_variants.yaml
> Added author page for Ekatrina Borisova

- data/xml/2020.emnlp.xml
- data/xml/2021.acl.xml
- data/xml/2021.emnlp.xml
- data/xml/2022.emnlp.xml
- data/xml/2024.acl.xml
- data/xml/2025.findings.xml
- data/xml/S17.xml
- data/yaml/name_variants.yaml
> Added author page for Ming Wang

- data/xml/2025.jeptalnrecital.xml
1. [x] In the Github sidebar, add the PR to the current milestone
1. [x] In the Github sidebar, add the PR to the "Anthology Work Items" project
1. [x] In the Github sidebar, under "Development", link to the corresponding ingestion issue (if applicable)
1. [ ] For workshops, …
> Ingestion: jeptalnrecital
